### ISSUE TITLE
Cannot open the Program 

### ISSUE THREAD

**Issue by natrius** [mhoeher/opentodolist#11]
**Operating System:** Windows 10 - 1809

---------------------------
OpenTodoList.exe - System Error
---------------------------
The code execution cannot proceed because libopentodolist-common.dll was not found. Reinstalling the program may fix this problem. 
---------------------------

Tried with 3.9.0 with 32bit and 64bit.

**Comment by natrius** [comment]
Looks look, installed it now on Windows 10 :)

Better on GitLab further issues?

**Comment by mhoeher** [comment]
Thanks, good to hear it works :-)

I'll try to finish the next release the following days, so you should soon get a notification that the next official one can be downloaded from the usual sources.

For future issues, it would in fact be easier for me if you create them in Gitlab. The Github repository is only a mirror and used to publish the releases.
