### ISSUE TITLE
[Feature Request] Drag and drop ToDo lists

### ISSUE THREAD

**Issue by OldNick** [mhoeher/opentodolist#12]
It would be useful to be able to drag and drop (reorder) todo lists in a library - simply because some are less important and therefore require less attention.

Or it exists and isn't working for me...

It's a great app - it organises things pretty much as I think, just needs one or two tweaks to be perfect!

**Comment by mhoeher** [comment]
First of all: Its great to hear you like the app and find it useful :-)

Regarding your feature request: It definitely makes sense (and should be easy to implement, the logic in the backend is already implemented, it just needs to be integrated into the user interface).

I've created an issue in the project's [issue tracker](https://gitlab.com/rpdev/opentodolist/issues/218) for implementing it. It is planned for v3.11 (which hopefully will be released end of February, maybe earlier).

**Comment by mhoeher** [comment]
It took me a bit, but the feature is now implemented ;-) It is implemented in the latest release v3.11. Enjoy!
