### ISSUE TITLE
Snap app

### ISSUE THREAD

**Issue by mhalano** [mhoeher/opentodolist#13]
Since OpenTodoList was packaged for Flatpak I think could be packed for Snap.

**Comment by mhoeher** [comment]
Hi @mhalano,

thanks for the suggestion! I've [created an issue over at Gitlab](https://gitlab.com/rpdev/opentodolist/issues/223) to track this (as the project is developed there). I am currently quite busy and want to get some other changes in for the next release, but maybe I can manage to get this done within the release after (which is tentatively planned for end of March).

**Comment by mhoeher** [comment]
Hi @mhalano,

sorry, it took me quite a bit, but here you go: https://snapcraft.io/opentodolist

Hope the snap is working for you ;-)

I am closing this issue for now (support in the upstream Gitlab repository is currently merging to master). If you have further questions or problems using the snap, please feel free to raise another issue.
