### ISSUE TITLE
Any way to make the todo-lists more like a todo list? 

### ISSUE THREAD

**Issue by TobiasDev** [mhoeher/opentodolist#14]
I love the idea of this app, NextCloud sync, I own my data and all of that. I think it's amazing so far, however, I'm struggling a bit with the UI for a todo list. Maybe it's me not understanding the app, so I'm just trying to understand something. 

Is there anyway to make the Todo list act more like a todo list? Eg. making the list be the main part of a list. At the moment it feels a bit like the todo-list is like a note with todos inside of it. I mean, maybe that is the idea?

**Comment by mhoeher** [comment]
Hi @TobiasDev,

thanks for raising this issue, it's really appreciated!

One of the main ideas of the app is to have several different types of items (todo lists, notes and images, for the time being). For all of the more complex items (which currently means: Everything except tasks, i.e. the sub-todos inside todos) you are also able to use a certain set of *common, shared properties*, like the possibility to set due dates, attach files and also writes notes. Especially being able to add notes to everything currently makes the note items kind of redundant, but this is hopefully going to change soon (see [this issue](https://gitlab.com/rpdev/opentodolist/issues/197) in the issue tracker of the project on Gitlab).

Coming back to the todo lists: Yes, I would fully agree with you that the way a todo list page is currently rendered should be improved and the core intention of each item gets clearer. If you have concrete ideas on how you would imagine the todo list page to look like: Just let me know. Otherwise, I hope I will be able to do make up my mind about and start polishing the user interface soon.

**Comment by TobiasDev** [comment]
Ah, okay. :) Yeah, I might have some ideas, just need some time to draw them out and see. When I get some time I will do some suggestions and see what you feel! :)

**Comment by mhoeher** [comment]
Sounds great, thanks! Looking forward to your suggestions then ;-)

**Comment by TobiasDev** [comment]
Soooo, I just want to mention that I'm really a coder myself, and my drawing skills are, let's be nice to myself, bad. :D Anyway, I think the apps looks good, so I only tweaked the todo list part to look more like a todo list. :) 

![OpenList2](https://user-images.githubusercontent.com/5912371/59872132-5bbe7a80-9399-11e9-8b64-34a6ec0168e6.png)

**Comment by mhoeher** [comment]
Wow, thanks a lot for this detailed sketch up. I think I can agree with most of your input ;-)

In your sketch, you leave out all of the other stuff which currently also is in the todo list (notes, a due date for the list itself and so on). Do you have something in mind for this? If not, I'll make up my mind about this later (maybe just putting it below the finished todos or something like that).

Just for your information: [I've created an issue for this over at Gitlab](https://gitlab.com/rpdev/opentodolist/issues/234) (this is where the project is actually developed) and scheduled it for v3.14 (which I'll hopefully manage to release end of July). However, a little warning ahead: I'll be on vacation plus my job is also eating up quite a bit of my time, so maybe this might be released even later this summer. Hope that's still okay ;-)

**Comment by TobiasDev** [comment]
For the rest I actually left it out. I'm not sure you need that for a todo list? Since you also have a note function. :) Though, maybe I'm the only one not using it. :D 

I would probably make small icons next to the name of the list for them exactly. Let me add it to the sketch!

**Comment by mhoeher** [comment]
Personally, I at least use the notes feature quite often ;-) If I have a kind of smaller, encapsulated project, I:

* Create a todo list for it.
* Add general information (like some notes, documentation and stuff) as notes.
* And finally add todos to model concrete tasks I have to work on.

But yeah, the notes widget should only be added on demand so clear focus is on the list functionality.

**Comment by TobiasDev** [comment]
Yeah, I didn't really mean to remove it. Just didn't cross my mind. :) But I've added it to the new sketch here. Let me know if i missed something else. I didn't add attachments, but that could of-course also be added to the top. :) Just forgot the icon. 

![OpenList2Update](https://user-images.githubusercontent.com/5912371/59878708-40f40200-93a9-11e9-98ba-dd8745b07fa8.png)

**Comment by mhoeher** [comment]
Yeah, looks really good. I think I'll just "compile" this to code ;-)

**Comment by TobiasDev** [comment]
Also, don't stress about not getting it done in a month, or two. :) I think the software is quite amazing, esp. since I can use it with my NextCloud instance. :) So I'll wait! :)

**Comment by mhoeher** [comment]
Better don't write something like this or I'll get lazy xD

Also, I had no chance to work on the GUI for quite a while now, so resuming this instead of doing a lot of backend stuff is actually quite welcome ;-)

**Comment by TobiasDev** [comment]
Just a quick note, I believe it would be better if you remove the background images under scheduled and where the list are stored. For the list, just because it will look calmer, but for the scheduled tab it actully makes the tasks a bit harder to read. I showed the app to a friend with some sight problems and for him the tasks where hard to read. :) Its just another suggestion, but I believe it might help other people with the same problems.

**Comment by mhoeher** [comment]
That's indeed very valuable and important feedback. I've never realized that these backgrounds could potentially cause issues for someone using the app.

I created [this issue](https://gitlab.com/rpdev/opentodolist/issues/238) in Gitlab and scheduled it for v3.13 (which is planned to be release end of this month). It should actually be a quick one to fix ;-)

**Comment by TobiasDev** [comment]
Sorry!!! I forgot that we said we should move over to Gitlab with this stuff. I'll log in there now if I have anything else to write! :)

**Comment by mhoeher** [comment]
No problem ;-)

**Comment by mhoeher** [comment]
Hi @TobiasDev,

It took me a while, but I finally released v3.14 of OpenTodoList, which also includes the refactored todo list page (plus all of the other suggestions you made). In the hope of not having missed something in this issue, I close this one as well.

Thanks again for all your input and hope to hear some further ideas for improvement rather soon ;-)
