### ISSUE TITLE
any plans for ios?

### ISSUE THREAD

**Issue by somedevreally** [mhoeher/opentodolist#17]
great app and thanks for all the development, any plans for ios devices?

thanks

**Comment by mhoeher** [comment]
Hey, thanks for the feedback.

Regarding iOS: Yes, it is in fact on my todo list and even in the issue tracker over at gitlab.com: [rpdev/opentodolist#231](https://gitlab.com/rpdev/opentodolist/issues/231).

I actually hope that porting the app should be relatively straightforward, however, I cannot promise anything (this would be my first ever iOS app, so no clues what possible could and will go wrong doing this :wink:).

I'll update this issue once there are any news on the topic!

**Comment by somedevreally** [comment]
awesome, and i sure you will do just great with ios too.
we are the Guinea Pigs!!!!! we will test it and make it better

**Comment by mhoeher** [comment]
Hey, just to provide some updates: I meanwhile managed to build the app for iOS, get a developer account and upload everything required to the app store for review.

The review is currently running, so the app should soon be available for general availability. I'll update this issue once again the review is done.

**Comment by somedevreally** [comment]
can't wait to test, awesome

**Comment by mhoeher** [comment]
Okay, another short update. While the review for a release to the app store is still ongoing, the app can meanwhile be tested using TestFlight. If you're interested, here is the link to join testing the app:

https://testflight.apple.com/join/u8GQYkgR

**Comment by somedevreally** [comment]
works great, I created library on nextcloud and synced between Android and iPhone.
though I manually synced, I'll test when it will sync automatically.
awesome and thanks

**Comment by mhoeher** [comment]
Cool, good to hear.

One question: What do you mean by "synced manually"? Actually, after doing any changes, the app automatically uploads changes to the server. On the other side, it will pull changes when starting up or after a predefined timestamp (I think, 10min). Currently, the app will not continue running in the background (however, as there is no "reminder" feature yet, this shouldn't hurt, as new items will be pulled when starting the app).

**Comment by somedevreally** [comment]
ok so I did not wait for 10 minutes to check

**Comment by mhoeher** [comment]
Just for the records: The approval is through and I just released the app to the App Store. So everyone can now simply find and install it on iOS.

I am closing this issue (as the port and release of the app for iOS is technically done). In case you find any issues, please just add new specific issues for them ;-)
