### ISSUE TITLE
problem with xubuntu 18.04.3

### ISSUE THREAD

**Issue by b3rt0** [mhoeher/opentodolist#18]
Hi, it looks like a great app, I tried to use it but I ran into problems. It was installed from the software center of xubuntu, which installs the snap, after that I try to run the app by clicking the icon but nothing happens, then I ran /snap/bin/opentodolist
from the CLI but I got the following message:
"
You need to connect this snap to the kde-frameworks-5-core18 snap.

You can do this with those commands:
snap install kde-frameworks-5-core18
snap refresh kde-frameworks-5-core18
snap connect opentodolist:kde-frameworks-5-plug kde-frameworks-5-core18:kde-frameworks-5-core18-slot
"
Should I follow those steps? or something else is going on?

Thank you!

**Comment by mhoeher** [comment]
Hey, thanks for raising this issue.

Yes, currently, running the `snap connect ...` command is okay and necessary to get the app working. The background is, that OpenTodoList requires the Qt libraries in a relatively new version. So in order to have them available, I am using some KDE "base snaps", i.e. snaps that solely provide libraries for other snaps to use.

Unfortunately, it seems that these base snaps are not going to be installed with the app snap itself :disappointed: 

I will check if I can change something to install the base snap automatically (or find some other way to get the required Qt libraries). Until then, please run the mentioned commands and the app should start just fine.

**Comment by mhoeher** [comment]
Just for the sake of completeness: I opened [this issue](https://gitlab.com/rpdev/opentodolist/issues/256) over on the GitLab project to track further improvement on this topic.

**Comment by b3rt0** [comment]
Hello again, I tried running the three commands, the first two run ok, but the last one throws the following error:
error: cannot perform the following tasks:
- Connect opentodolist:kde-frameworks-5-plug to kde-frameworks-5-core18:kde-frameworks-5-core18-slot (connection not allowed by slot rule of interface "content")
May be I'm not running them appropriately ...? 
thanks for any help

**Comment by mhoeher** [comment]
This is strange. I ran these commands myself on Sunday to verify everything is still working and they just succeeded. So to be honest: I have for now no clue what might be wrong :disappointed: 

I will try to double check this evening if I can reproduce this.

In case I can't, you could either wait for a standalone snap (however, this might require some time to implement, as snap does not make this an easy endeavour) or try to use e.g. the AppImage or Flatpak version of the app (both should also run fine on Xubuntu, see e.g. [this link](https://flatpak.org/setup/Ubuntu/) on how to set up Flatpak).

**Comment by mhoeher** [comment]
Hm... today, when I rerun these commands, I had the same errors :-(

So it seems something changed with respect to these content snaps. I will look into this and try to find out what's wrong.

**Comment by mhoeher** [comment]
Another update: I updated the snap definitions and released a new version (a `snap refresh opentodolist` should pull in the update). Afterwards, running the commands to connect to the KDE base snap should succeed.

I once more read through [this wiki page](https://community.kde.org/Guidelines_and_HOWTOs/Snap) and according to it, we unfortunately cannot get rid of manually running these commands to finish the snap installation. This is unfortunate, so I'll check if I can somehow get rid of the KDE content snap dependency in the future.

**Comment by b3rt0** [comment]
I tried it again, and now the commands ran perfectly, thank you very much.
I also noticed improvement to in the last update to the android version,
before that the rigthmost icon was kind of hidden. Thanks once again.

**Comment by mhoeher** [comment]
Cool, good to hear :smile: 

By the way: In case you notice such rendering issues like you did in the Android app, don't hesitate to report them as well. :wink:

**Comment by mhoeher** [comment]
Just another short update on this: Via [this issue](https://gitlab.com/rpdev/opentodolist/issues/256) I changed the build of the snap. Future versions will no longer require the KDE content snap, so running any commands on the CLI is no longer necessary.

This change will be rolled out with the next version (which will hopefully be made available in a few days).
