### ISSUE TITLE
Add it to AUR

### ISSUE THREAD

**Issue by tiotrom** [mhoeher/opentodolist#22]
Hi! Do you plan to add this to AUR? Thanks!

**Comment by mhoeher** [comment]
Up to now I had no plans to add this to AUR. I try to provide the app via mechanisms that should work across all distributions (namely, it is provided via Flatpak, Snap as well as an AppImage).

I will check if adding it to AUR is feasible and also how much work this would mean. Currently, development of the app is pretty much a one-man-show, so I have to ensure I still have enough time doing development ;-)

If you know someone who would volunteer to maintain the AUR build files, I would definitely be in and help getting things up and running as well.

**Comment by mhoeher** [comment]
Tracking ticket on Gitlab: https://gitlab.com/rpdev/opentodolist/-/issues/309.

**Comment by JohnAntoineG710** [comment]
This could be done with the AppImage version of the app, and the AUR could be used just as an easy way to install/update

**Comment by mhoeher** [comment]
Hm... I could check if this would help easing the process. However, I am rather afraid from the actual process of getting it into AUR ;-) Anyway, I tentatively scheduled the Gitlab issue for this for v3.24 (which - if everything goes well - will be released in June, so with a bit of luck, it should then be installable directly from AUR).

**Comment by JohnAntoineG710** [comment]
Check out this an example [Joplin AUR appimage](https://aur.archlinux.org/packages/joplin-appimg/)
The PKGBUILD file is pretty simple.
And you wouldn't have to keep up with arch's bleeding edge libraries because it's an appimage at the end of the day, so it wouldn't matter that much if your package gets flagged out of date.

**Comment by mhoeher** [comment]
Thanks, I'll give it a try ;-)

**Comment by mhoeher** [comment]
I know, a bit late, but better this than never :-o

I managed to get a build recipe for the app to AUR, see here: https://aur.archlinux.org/packages/opentodolist/

Would be great if you guys (if you're still interested) could test this a bit. The package will be built against the system Qt installation (and hence should be significantly smaller than the AppImage). 

The AUR package currently points to the most recent release (v3.25). If possible, I'd like to automate updating the AUR recipe automatically upon a release (so for this reason I keep the [implementation issue in Gitlab](https://gitlab.com/rpdev/opentodolist/-/issues/309) open for the time being).

**Comment by tiotrom** [comment]
That's awesome. I could not build it tho. I get this error:
`: NotePageTest::initTestCase()
PASS   : NotePageTest::persistence()
PASS   : NotePageTest::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 1ms
********* Finished testing of NotePageTest *********
make[2]: Leaving directory '/var/tmp/pamac-build-tio/opentodolist/src/OpenTodoList/build/test/notepage'
FAIL!  : LibrariesItemsQueryTest::run() 'destroyed.wait()' returned FALSE. ()
   Loc: [/var/tmp/pamac-build-tio/opentodolist/src/OpenTodoList/test/librariesitemsquery/test_librariesitemsquery.cpp(147)]
PASS   : LibrariesItemsQueryTest::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 5198ms
********* Finished testing of LibrariesItemsQueryTest *********
make[2]: *** [Makefile:726: check] Error 1
make[2]: Leaving directory '/var/tmp/pamac-build-tio/opentodolist/src/OpenTodoList/build/test/librariesitemsquery'
make[1]: *** [Makefile:1290: sub-librariesitemsquery-check] Error 2
make[1]: Leaving directory '/var/tmp/pamac-build-tio/opentodolist/src/OpenTodoList/build/test'
make: *** [Makefile:790: sub-test-check] Error 2
==> ERROR: A failure occurred in check().
    Aborting...
`

**Comment by mhoeher** [comment]
Just try again. Since some time there is a new instability in one of the test cases (nothing critical and not actually impacting the behavior of the app - the test "just" needs to get fixed).

**Comment by tiotrom** [comment]
It is a bit weird since now I get this:
`==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> WARNING: Package contains reference to $srcdir
usr/lib/libqlmdb.so.1.0.0
usr/lib/libqlmdb.prl
usr/lib/libopentodolist-core.prl
==> Creating package "OpenTodoList"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: OpenTodoList 3.25.0-1 (Wed 12 Aug 2020 01:42:15 PM CEST)
==> Cleaning up...
`
Yet in pamac I do not see it as being installed...nor is it in my apps section...very weird

**Comment by mhoeher** [comment]
May I ask what exactly you ran? For me, it looks like you only build the package (using `makepkg`), is this correct? This will only create a file which is suitable for being installed via `pacman`.

However, in doubt, I am not sure and would have to debug this on my own, as I am not a regular Arch Linux user ;-)

**Comment by tiotrom** [comment]
I am using TROMjaro (Manjaro based) and Manjaro's Pamac application to install all packages. https://wiki.manjaro.org/index.php/Pamac

**Comment by mhoeher** [comment]
okay, never worked with this before ^^'

Anyway, I just realized there still seems to be some issue with the PKGBUILD file. Nothing too bad, will try to solve this tonight or tomorrow and update you here when something is available.

In the meantime, I just tried (in a container, so I could not test if the resulting app would actually run) the following (basically, the plain AUR way to install such packages):

```bash
git clone https://aur.archlinux.org/opentodolist.git
cd opentodolist
makepkg -si
```
This will install the prerequisites, build the app and install it. Afterwards, you can run it by simply running

```bash
OpenTodoList
```

on the command line. Also, the app should in theory install a link which should show up in e.g. the applications menu.

**Comment by tiotrom** [comment]
I would prefer to try it via Pamac :D. As I am used to that and I would love to see it working as such, like all AUR packages. If it is possible to make it work as such....

**Comment by JohnAntoineG710** [comment]
Hi Martin, for some reason, I am having trouble fetching a couple of repos! I will try again later tonight, maybe it's a problem with my internet connection.

I think my testing environment is different than Tiotrom's, I'm running vanilla arch and installing via YAY.

If I couldn't fetch everything through YAY, i'll try installing the package using `makepkg`. If the installation went through, then we could debug the reason it's not working with AUR managers like `YAY` or `PAMAC`.

**Comment by mhoeher** [comment]
Hey guys,

I found an issue in the `PKGBUILD` file (the `pkgname` uses capital characters which seems to cause issues somehow). Anyway: I updated it and pushed to AUR, so maybe you could try again and let me know if installation now works for you via your tools of choice? Thanks a lot!

@JohnAntoineG710 As you already mentioned it... would you mind filing some issues about what exactly you found to be buggy? This is a hobby project of mine so consequentially there is no guarantee that these might get fixed super timely, but as author of it I'd still like to make it somehow as stable as possible (especially since I am using it on my own on a daily basis, so I'd prefer to not run into any bad surprises on my own :sweat_smile:). Thanks!

**Comment by tiotrom** [comment]
First try it showcased the same error as above, second it worked! Now all works fine I can open it and all that. But maybe that first error needs to be fixed. I used TROMjaro (arch linux) + Pamac

**Comment by mhoeher** [comment]
Thanks for giving it a try! Do you by chance have a log of the first try that failed again? I could imagine this could be a caching issue, that was solved by pamac pulling the update only on the second try, but who knows...

**Comment by mhoeher** [comment]
As the app is not available in AUR for some time and there were no further complaints, I am closing this issue now.

If you still have issues, please open up a new ticket here (ideally attaching some logs of what potentially goes wrong with the installation) :wink:
