### ISSUE TITLE
Webdav sync, not writing to server

### ISSUE THREAD

**Issue by uGeek** [mhoeher/opentodolist#28]
Hi
I have tested the application with android, appimage and snap, and none of the three write the directories and libraries to the server.

I have tried other applications like joplin, orgzly, foldersync, purewriter, ... and the server works correctly

![Captura de pantalla de 2020-11-22 19-58-26](https://user-images.githubusercontent.com/27757712/99914377-550a0480-2cfd-11eb-85c4-ac984725c578.png)

Thank you very much and very good application

**Comment by mhoeher** [comment]
Hi @uGeek,

sorry to hear the sync is not working for you. From the logs you provided, I guess the following happens:

- This is the "first time" sync of the library (yes, you probably tried several times, but usually on the first time we sync some "preparations" are done and on previous runs this might already have failed).
- The app realizes that it needs to create the top-level "OpenTodoList" folder. This is the folder where it puts all the libraries in you create.
- When sending an appropriate request to the server, it fails with a "ContentConflictError".

Unfortunately, this alone won't be enough to properly understand the issue. So if possible, could you please provide the following information:

- The version of OpenTodoList you are using (you find it in the side bar by opening the `About...` page).
- What server you try to use for the sync (i.e. is it a NextCloud or ownCloud instance or another WebDAV server).
- Especially in the case of a "generic" WebDAV server, it would be great if you could also provide information like the URL you used to connect to the server.

If you prefer, you can send me the information via mail (martin@rpdev.net) if you don't want to disclose information like the used URLs.

Thanks a lot in advance!

**Comment by mhoeher** [comment]
Hi @uGeek,

thanks for providing some details on how to reproduce the issue offline!

I created an [issue over at GitLab](https://gitlab.com/rpdev/opentodolist/-/issues/387) for fixing this. In fact, I already was able to tackle one particular issue (the creation of remote folders). However, the sync - at least with the current test server I have - does still not run through, but this could also be a server configuration issue.

If you like, you can download development builds of the app from [this pipeline](https://gitlab.com/rpdev/opentodolist/-/pipelines/222853733) and give it a try already. Maybe that change already is enough to make the app work against your production server?

**Comment by uGeek** [comment]
thank you

I will try it

**Comment by mhoeher** [comment]
Just for the records: The issue mentioned above has been merged and the fix which caused the folder creation is part of the most recent release (v3.29). If you still experience issues, please let me know (ideally providing new logs).

**Comment by mhoeher** [comment]
Closing this - I hope the above fixed it for you. If you still encounter issues, please let me know (and reopen the issue or create a new one :wink:).
