### ISSUE TITLE
Feature request: Sort items manually

### ISSUE THREAD

**Issue by huste** [mhoeher/opentodolist#32]
I am aware that there is only a parent-relationship between items, but it would really be awesome, if items could be dragged to reorder them. My main use case for this app is a shopping list that I share with other people. And I always order items so taht they're in the same order as they are in the shops.

Maybe an integer "order" attribute would work, where in case of a conflict same order numbers are ordered as they are now. and when syncing, the order numbers are reassigned to reflect the current sort order.

**Comment by mhoeher** [comment]
Good to know I am not the only one with this particular use case :wink: 

Regarding sorting: You actually should be able to do so. You can long press-and-hold on any item and then drag it around to reorder them. This works in the top level library view, for todo lists and also task lists (the only exception in fact is the schedule view).

Just make sure that you have manual sorting enables (in case of todos):

![manual-sorting](https://user-images.githubusercontent.com/1911135/104780655-5eee3800-5781-11eb-9c25-1ef05e92ee3c.gif)

This is the default setting, however, maybe you changed it (in this case, a press-and-hold will trigger show a context menu with further actions for the item).

**Comment by huste** [comment]
Aaah, I completely missed that. It's not standard behaviour on Android to have items dragged after a long press. Thanks for the pointer, closing this one.

**Comment by mhoeher** [comment]
Yeah, to be honest, I wonder if this behaviour should be changed. It is sub-optimal, as a long-press has different functions depending on the sort mode and as you said, it is not default (I basically implemented it like this because the same was done by Wunderlist, which I used for a long time and which hence kind of served as an inspiration for some of the functions of the app :wink:).
