### ISSUE TITLE
background indication of completeness with subtasks is somewhat inconsistent

### ISSUE THREAD

**Issue by huste** [mhoeher/opentodolist#33]
I have a TODO list with 2 items and both have 4 sub items.

When I check all 4 sub items for the first main item, the grey background completeness indicator of the main item shows approximately 10%.
When I check all 4 sub items for the second main item, the grey background completeness indicator of the main item shows approximateliy 60%

The individual steps, when checking 1, 2, 3 or all 4 sub items are even spaced.

**Comment by mhoeher** [comment]
Thanks for reporting this. I just tried to reproduce it here, however, for me it is working :open_mouth: 

Does this always happen for you? Or just one time? Does restarting the app somehow help?

Also, could you please shed some light on your setup? Is this happening on a desktop system (Windows, macOS, Linux) or a smartphone (Android, iOS)?

**Comment by huste** [comment]
Ah sorry, I completely missed telling you my environment - I'm not used to having platform independent applications :)

Here's two screenshots, also to illustrate #31
I'm on Android 9 on a Samsung Galaxy Note 8. So it's not a very small display, but a sub TODO list only shows 6 items. One item is as high as three lines. It could be significantly narrower, I think.

![Screenshot_20210115-232638](https://user-images.githubusercontent.com/9739281/104790421-66b8d700-5797-11eb-986d-102abab27021.jpg)
![Screenshot_20210115-232651](https://user-images.githubusercontent.com/9739281/104790426-68829a80-5797-11eb-84de-da25efecec63.jpg)

As you can see, the indicator in the background is very short. Can it have something to do with deleted items? When I add and remove items and reopen the app, ticking 4 of 4 remaining items makes the bar a little bit shorter than it was before.

This also happens in the Windows application.

**Comment by mhoeher** [comment]
Bingo, *deleted* was the missing piece of the puzzle ;-) Just in case you are interested:

- The app internally maintains a database for all items. It basically uses two tables:
- One table is an item ID to Item Data mapping.
- The second maps an item ID to a list of item IDs of its "child" items.

I guess what happens in this case is, that when we delete items, we only remove the entry in the first table, but keep stale entries in the second one. However, for finding the number of total items, we obviously don't check if the child item no longer exists.

I created a Gitlab issue to fix this: https://gitlab.com/rpdev/opentodolist/-/issues/395

**Comment by huste** [comment]
Oh, how much I love database inconsistencies :) Thanks for opening the gitlab issue, let's close this one here
