### ISSUE TITLE
auto-wrap / line-break for longer todo list titles

### ISSUE THREAD

**Issue by HackintoshHD** [mhoeher/opentodolist#36]
Apparently there is no way to display a longer todo list title entirely, because OpenTodoList 3.31.1 does not auto-wrap longer todo list titles to a second line of text:

![OpenTodoList_no_auto-wrap](https://user-images.githubusercontent.com/2894628/106680073-2ee6c780-65be-11eb-84e3-ef15bb2fedf4.png)

In fact, there even is no way to scroll through such a title, you really need to open the card in an individual view to read the title entirely.

Would it be possible to add an auto-wrap feature for todo list tiles or to at least display an arrow-right button for scrolling through the title?

**Comment by mhoeher** [comment]
Lines intentionally do not wrap. The idea of the "overview" page is, that you see your top level items in a compact way and quickly navigate where you need to. If titles would wrap (indefinitely) items would have varying header heights which I'd like to avoid (for now).

What I can think of (and what should be easy to implement): I could add tooltips. So on a Desktop system, you could hover the item title and - if it is too long - a tooltip with the full title will be shown. WDYT?

Adding some "control" (like a small button) where you can click on to see the full title is also doable.

**Comment by HackintoshHD** [comment]
Thanks for reacting that fast, @mhoeher. I admit long titles are to some extend a "layer 8" problem and can certainly be avoided by a strict user discipline. In some situations, however, e.g. if you work in a team and have agreed to a unified title 'syntax', that will be rather difficult.

Tooltips would already be a big help. Another solution of the problem I could imagine would be the way Adobe has applied to input fields of PDF forms: Once your cursor arrives at the end of an input field, they start to decrease font size with every further letter (within certain limits of readability, of course). From a typography's perspective, this may not the nicest looking solution possible, but it undoubtfully has the advantage of a) not wrapping titles into multiple lines and b) not increasing the tasklist 'card's' overall width at the same time.

**Comment by mhoeher** [comment]
Hm... decreasing font size to fit the title also could be an interesting solution. I will test this out this evening (or latest this weekend) - will update you if there's something to test out :wink:

**Comment by mhoeher** [comment]
Just a short update: I did not find the time to look into this, but added an issue for the next monthly release (see https://gitlab.com/rpdev/opentodolist/-/issues/407) as implementing something nice shouldn't be a big thing.

**Comment by HackintoshHD** [comment]
No problem & cool, thank you very much! 👍

**Comment by mhoeher** [comment]
Finally found some time to work on this. I think the solution now should work quite fine:

- The text is scaled down dynamically until a certain, minimal font size (currently, 6pt) is reached.
- After that, the title is truncated. If this happens, one can hover the title to show a tooltip with the full content (well, this currently only works on Desktop systems with a mouse/cursor).

Would be great if you could give it a try and let me know if this fulfils your needs. A [pipeline](https://gitlab.com/rpdev/opentodolist/-/pipelines/255097176) is running over at GitLab. You can find APKs attached to the `sign_apks` job (once it is finished).

**Comment by HackintoshHD** [comment]
Allright, installed from https://gitlab.com/rpdev/opentodolist/-/jobs/1024995106/artifacts/file/build-macos/app/OpenTodoList.dmg and tested:

Everything concerning todo list titles works like a charm and the solution you've found is really elegant I have to say. In fact, nearly all of my formerly truncated todo list titles are now fully displayed and I honestly wouldn't have noticed their smaller font size if you hadn't told me about it, it's really very subtle. I literally had to create a new exageratedly long todo list title to get to the point where OpenTodoList would truncate a 6pt todo list title, so this feature is now really, really workable in practice.

Thank you so much! 👍

**Comment by mhoeher** [comment]
Thanks for testing! I merged the change, so it'll be part of the next release :wink:
