### ISSUE TITLE
Not compilable from sources

### ISSUE THREAD

**Issue by tieugene** [mhoeher/opentodolist#38]
According to [documentation](https://github.com/mhoeher/opentodolist/blob/master/doc/building-with-cmake.md):
```
wget -O opentodolist-3.31.2.tar.gz https://github.com/mhoeher/opentodolist/archive/3.31.2.tar.gz
tar xf opentodolist-3.31.2.tar.gz
cd opentodolist-3.31.2
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RELEASE ..
CMake Error at CMakeLists.txt:4 (include):
  include could not find load file:
    ./3rdparty/qt-cmake-android/cmake/autodetect-android-build.cmake
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at 3rdparty/CMakeLists.txt:1 (add_subdirectory):
  The source directory

    .../opentodolist-3.31.2/3rdparty/qtkeychain

  does not contain a CMakeLists.txt file.


CMake Error at 3rdparty/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    .../opentodolist-3.31.2/3rdparty/qlmdb

  does not contain a CMakeLists.txt file.

CMake Warning at lib/CMakeLists.txt:116 (find_package):
  By not providing "FindKF5SyntaxHighlighting.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "KF5SyntaxHighlighting", but CMake did not find one.

  Could not find a package configuration file provided by
  "KF5SyntaxHighlighting" with any of the following names:

    KF5SyntaxHighlightingConfig.cmake
    kf5syntaxhighlighting-config.cmake

  Add the installation prefix of "KF5SyntaxHighlighting" to CMAKE_PREFIX_PATH
  or set "KF5SyntaxHighlighting_DIR" to a directory containing one of the
  above files.  If "KF5SyntaxHighlighting" provides a separate development
  package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
```

**Comment by tieugene** [comment]
Qmake:
```
bash-5.0$ LC_ALL=C qmake-qt5 CONFIG+=release ..
Info: creating stash file /mnt/shares/home/eugene/rpmbuild/BUILD/opentodolist-3.31.2/build/.qmake.stash
Info: creating cache file /mnt/shares/home/eugene/rpmbuild/BUILD/opentodolist-3.31.2/build/.qmake.cache
Checking for qtkeychain... no
Checking for libsecret... no
Project MESSAGE: Configure summary:
Project MESSAGE:     Install Prefix:         
Project MESSAGE:     Binary Install Prefix:  /usr/local/bin
Project MESSAGE:     Library Install Prefix: /usr/local/lib
Project MESSAGE:     QtKeychain:             Built-in
Project MESSAGE:     Libsecret:              Not Found
Project MESSAGE:     Update Service:         Disabled
Project MESSAGE:     Test against NextCloud: Disabled
Project MESSAGE:     Test against ownCloud:  Disabled
Project MESSAGE:     AppImage Extras:        Disabled

bash-5.0$ LC_ALL=C make
cd 3rdparty/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /mnt/shares/home/eugene/rpmbuild/BUILD/opentodolist-3.31.2/3rdparty/3rdparty.pro CONFIG+=release ) && make -f Makefile 
make[1]: Entering directory '/mnt/shares/home/eugene/rpmbuild/BUILD/opentodolist-3.31.2/build/3rdparty'
cd qlmdb/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /mnt/shares/home/eugene/rpmbuild/BUILD/opentodolist-3.31.2/3rdparty/qlmdb/qlmdb.pro CONFIG+=release ) && make -f Makefile 
Cannot find file: /mnt/shares/home/eugene/rpmbuild/BUILD/opentodolist-3.31.2/3rdparty/qlmdb/qlmdb.pro.
make[1]: *** [Makefile:48: sub-qlmdb-make_first] Error 2
make[1]: Leaving directory '/mnt/shares/home/eugene/rpmbuild/BUILD/opentodolist-3.31.2/build/3rdparty'
make: *** [Makefile:100: sub-3rdparty-make_first] Error 2
```

**Comment by mhoeher** [comment]
Please do not use the (auto generated :wink:) source archives that GitLab/GitHub are creating.

OpenTodoList uses `git submodule` to include some required third party modules. Currently, you cannot built if these modules are not present in source form. Unfortunately, neither GitLab nor GitHub include *sources of submodules* in the archives.

Instead, clone the repository (*recursively) and check out the desired version:

```bash
git clone --recursive git@gitlab.com:rpdev/opentodolist.git
cd opentodolist
git checkout 3.31.2
```

Also, please take into account [this issue](https://gitlab.com/rpdev/opentodolist/-/issues/325). In short, the app recently was focusing on `qmake` only. I started to revive the `cmake` build (will be part of the next release) and probably retire the `qmake` one instead (which makes sense as Qt is heading in the same direction).

**Comment by tieugene** [comment]
> ```shell
> git clone --recursive git@gitlab.com:rpdev/opentodolist.git
> ```

```
bash-5.0$ LC_ALL=C git clone --recursive git@gitlab.com:rpdev/opentodolist.git
Cloning into 'opentodolist'...
git@gitlab.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Please create compilable sources in Downloads - or _really_ usable manual.

**Comment by mhoeher** [comment]
Sorry, the URL is only usable if you have a login on GitLab (as you have to upload an SSH public key to authenticate with). Please use the HTTPS URL instead:

```bash
git clone --recursive https://gitlab.com/rpdev/opentodolist.git
```

Regarding:

> Please create compilable sources in Downloads - or really usable manual.

As I said, **I am not creating these source archives actively**. Dunno if this even can be turned off...

Regarding documentation... I know that missing or bad documentation sucks. However, please keep in mind that I am developing this app in my scarce free time. When doing so, I'd (as every developer) prefer to work on new features instead of bullet proof documentation. :wink: 

However, as the app is open source, everyone is welcome to contribute, either on GitLab (which would be preferred, as this is where the app is mainly developer) or also here on GitHub. The documentation you linked to is part of the repository, so contributing to it is as simple as creating a PR :+1:

**Comment by tieugene** [comment]
I have no enough power to contribute but can maintain for RH based distros (RH, CentOS, Fedora).
The only thing that required to start packaging - tarball.
And to compile before.
Now it is better, but...
[opentodolist.log.gz](https://github.com/mhoeher/opentodolist/files/6086852/opentodolist.log.gz)

**Comment by mhoeher** [comment]
Regarding the tarball... I can check if I somehow can change the behaviour, but my guess would be the answer is no :disappointed: 

On which distribution do you currently try to build the app? If it is on Fedora, it should work, you just need all the dependencies. Have a look at this changeset: https://gitlab.com/rpdev/opentodolist/-/merge_requests/249 

This is the change that will also restore the `cmake` based build. It will add a Fedora based CI test via the script [`ci/fedora-build.sh`](https://gitlab.com/rpdev/opentodolist/-/blob/325-revive-cmake-support/ci/fedora-build.sh) (actually, two, one building with `cmake` the other one using `qmake`). The CI is currently passing, see e.g. https://gitlab.com/rpdev/opentodolist/-/jobs/1071369007

Of course, on recent releases or master, the `cmake` variant won't work, but you definitely should be able to build using `qmake`. I guess, all that is missing is the `QtRemoteObjects` module (at least the build log hints at that).

For other distributions (RHEL/CentOS): The app makes use of some rather recent Qt features, so I am not sure it is can be built using the Qt packages from the main repositories). Currently, I would say one at least requires Qt 5.14.x (at least this is the lowest Qt version used in the CIs of the app). Older Qt versions might be possible to support, but that definitely would require a bit of work...

**Comment by tieugene** [comment]
It is Fedora 33 (x64), Qt 5.15.2
Cmake really not works (`By not providing "FindKF5SyntaxHighlighting.cmake" in CMAKE_MODULE_PATH`).
QtRemoteObjects is provided by qt5-qtremoteobjects-devel package but this is not defined in build instruction nor by qmake messages.
Now `make` pass ok. Don't know about `make install` (I _never_ install any application without packaging).

**Comment by mhoeher** [comment]
You can run e.g.

```bash
DESTDIR=/tmp/OpenTodoList make install
```

to install the files into a temporary location (in the example above, `/tmp/OpenTodoList`). That way you can inspect the target structure that would have been created.

**Comment by mhoeher** [comment]
By the way: I just checked and didn't find a way to tell either GitLab nor GitHub to include code of `git submodule`s in the source archives, hence... https://gitlab.com/rpdev/opentodolist/-/issues/415

**Comment by mhoeher** [comment]
Okay, just wrote a little script, which will - for future releases - automatically build a full source archive (actually, two: One `*.zip` and one `*.tar.gz`). These will be included in releases on GitHub as well.

For now, I have manually built these for the most recent release v3.31.2 and manually uploaded them, so if you like, please find them in the GitHub Release: https://github.com/mhoeher/opentodolist/releases/tag/3.31.2

**Comment by tieugene** [comment]
> Okay, just wrote a little script, which will - for future releases - automatically build a full source archive (actually, two: One `*.zip` and one `*.tar.gz`). These will be included in releases on GitHub as well.
> 
> For now, I have manually built these for the most recent release v3.31.2 and manually uploaded them, so if you like, please find them in the GitHub Release: https://github.com/mhoeher/opentodolist/releases/tag/3.31.2

Seems this is the best <s>dirty hack</s> solution as for now.
Thank you, I will try to package it (if you are interesting in).

**Comment by tieugene** [comment]
It is compilable now but not installing due #39, so I close the ticket.
