### ISSUE TITLE
Wrong libdir

### ISSUE THREAD

**Issue by tieugene** [mhoeher/opentodolist#39]
By default libraries installing into /usr/local/lib (or /usr/lib if INSTALL_PREFIX=/usr).
Right libs path is /usr/lib64 on x64 hosts and /usr/lib on x32 ones.
Fedora 33 x64.

PS. BTW good idea to replace INSTALL_PREFIX with PREFIX (default variable in autotools etc).

**Comment by mhoeher** [comment]
Will be fixed via [this issue](https://gitlab.com/rpdev/opentodolist/-/issues/325): Using the `cmake` build (once it is available again), the proper install path should be used (as `cmake` handles this correctly). I will not fix this for the `qmake` based build, as this one is going to be phased out once `cmake` works for all target platforms the app is supported for.

The `cmake` based build will be available starting with the next release (which should be available within the next few days).

Regarding:

> PS. BTW good idea to replace INSTALL_PREFIX with PREFIX (default variable in autotools etc).

Might be, but see above :wink: I won't introduce any major changes to the `qmake` based build. For `cmake`, it uses its own well defined set of variables for that purpose.
