### ISSUE TITLE
Building requirements

### ISSUE THREAD

**Issue by tieugene** [mhoeher/opentodolist#40]
According to [documentation](https://github.com/mhoeher/opentodolist/blob/master/doc/building-with-cmake.md):
> The following components are required to build OpenTodoList:
- Qt >= 5.10.0
- CMake >= 2.8.11 (optional)

This is not enough if you not use _whole_ of Qt.
In practice (Fedora 33 Linux):
- qt5-linguist
- qt5-qtbase-devel (Qt5Core etc)
- qt5-qtdeclarative-devel (Qt5Qml, Qt5Quick)
- qt5-qtremoteobjects-devel (Qt5RemoteObjects)

**Comment by mhoeher** [comment]
I created an issue over at Gitlab: https://gitlab.com/rpdev/opentodolist/-/issues/416

By the way... if you plan to raise some more issues, I'd be glad if you could directly do it in Gitlab if possible, this would spare me some work :wink: 

One thing I'd like to mention: The linked instructions are assuming you use the official Qt binaries, where there is no break down into dedicated libraries of the "core" Qt packages. This is basically a Linux-distro-only thing (and these instructions are on purpose rather generic). However, I agree it would probably make sense to add the list of known packages where possible.

**Comment by tieugene** [comment]
> This is basically a Linux-distro-only thing (and these instructions are on purpose rather generic). However, I agree it would probably make sense to add the list of known packages where possible.

You _must not_ to define requirements for each linux distro.
But this is good idea to pay attention to mainstream distros: RH (and successors), Debian (and successors), *SUSE.

**Comment by mhoeher** [comment]
Implemented via the above linked issue.

The new build instructions can be found [here](https://gitlab.com/rpdev/opentodolist/-/blob/development/doc/build-instructions.md).
