### ISSUE TITLE
Feature Request: Move subtask to new task

### ISSUE THREAD

**Issue by DocBe** [mhoeher/opentodolist#42]
I am using this tool for my daily GTD work. It is fabulous in terms of data security option (Nextcloud integration) and simple action item handling.
THANK YOU!
For a good project management I am only missing one option:

**Movement of "subtasks" as "tasks" from one tasklist to another.**

Any chance to implement this?

**Comment by mhoeher** [comment]
Well, it's just software, so a lot is possible here :wink: 

Just to make sure we're talking about the same thing: In OpenTodoList, the wording used is...

- There are **Todo Lists**, which are directly inside your library.
- A todo list can have arbitrary many **Todos**.
- A todo in turn can be broken down into **Tasks**.

So do you want to:

- *Promote* a task (i.e. move it from being inside a todo to a todo list)?
- Or do you want to just move a task from one todo into another one?

Both should be possible (the latter being slightly easier to implement than the former one, but both definitely doable).

**Comment by DocBe** [comment]
Thank you for the quick and positive feedback! That sounds promising.
Your second suggestion does actually already work very well (move a task from one todo into another one within one library).

What I mean is similar but a different layer movement within one library:

**Move a subtask from one todo into another todo and automatically convert it into a task.** So it is more or less an upgrade of a subtask to a task.

Current set-up: _Library -> ToDo -> Task -> Subtask:_ Tasks can be moved across all todos by “Move Todo into…” command.

Future set-up: add. to above even subtasks can be moved across all todos. By this a subtask is converted into a task.

Background is the following: The GTD method puts single tasks into a context. Those contexts (= todo list) are called e.g. Errands, Calls, @home, @office, waiting for… Within those contexts all single tasks are listed. In case a certain item needs more than one task for fulfillment it is called a project. Translating GTD to OpenTodoList means you create one library and set-up all contexts as a todo list. In order to manage projects I created a todo called “Projects”, listing all single projects as tasks. Related tasks for each single project are listed as subtasks. As soon as one task is ticked-off from a todo I would like to shift the next one from a project into another todo. Does this make sense to you?

**Comment by DocBe** [comment]
That sounds wonderful! Yes, keep it simple and implement a promote tool acc. to 1. and 2. Carrying out two actions is perfectly fine. Still better than deleting the task and adding a new todo into another todo list.

Thank you a lot! :-)

**Comment by DocBe** [comment]
Donation is coming, for the next coffee. ;-)

**Comment by mhoeher** [comment]
Hehe, thanks :wink: 

Just FYI: I created [an issue over on GitLab](https://gitlab.com/rpdev/opentodolist/-/issues/429) to implement this. I think implementation should be relatively straightforward, so it might be included in the coming release already (which is due beginning of April).

**Comment by mhoeher** [comment]
Good news: This feature will be part of the next release :wink: 

Here's a small video of it in action:

https://user-images.githubusercontent.com/1911135/113054878-38e60a80-91aa-11eb-9cb5-28cf344fc37e.mp4

Hope that's what you expected. In addition, you cannot only promote, but select the target todo list to promote the task into. By default, the parent todo list of the todo to which the task belongs is pre-selected in the dialog.

If you need something else, just let me know.
