### ISSUE TITLE
Sort itemsmanually

### ISSUE THREAD

**Issue by DocBe** [mhoeher/opentodolist#45]
Dear Martin, 

here is another idea for implementation into your great app to make it even better. Thank you for implementing the "promotion" of tasks already!

I realized that there is no way to select single ToDo's or Task's within a list and reorganize them (e.g. move ToDo 1 to position 10 etc.). Is there any option to do this via e.g. drag & drop or in case easier to develop to implement it by an alphanumeric filter? Drag & drop would be really user friendly but a filter would already help for a first shot.

Thank you a lot for checking!

**Comment by mhoeher** [comment]
Good news: Both is already implemented and available in the app :wink: 

You can reorder items in a library as well as todos inside a todo list and tasks inside a todo but long pressing on them and holding down the mouse (or keep touching the display on a touch device). Eventually, the item will be highlighted and you can drag it around to reorder it.

In addition, items in a library as well as todos can be sorted "automatically" (look for the icon with the combined arrow up + arrow down - click it to select one of the available sorting modes). Note that if automatic sorting is on, reordering by drag&drop is disabled (a long press/tap will in that case open the context menu).

I am aware that the manual reordering is well hidden. The next release of the app will make reordering items way easier. There will be an inline drag handle in each item which you can use to start a drag&drop without the long press first - at least inside todo lists.

Let me know what you think and if this already is what you are looking for :wink:

**Comment by DocBe** [comment]
Fabulous! That's exactly what is needed! I was not aware of this since automatic sorting was adjusted... Thank you for your fast und positive reaction. You can just close my issue and be sure to have a very happy app user (working very well on Mac and IPhone, connected to Nextcloud, of course).

**Comment by mhoeher** [comment]
Great to hear and also great to know the app works so well for you 😉 

If you have more ideas or questions, just file another issue. Until then, wishing you a lot of fun with the app!
