### ISSUE TITLE
Repeat todo once a year

### ISSUE THREAD

**Issue by Krit1960** [mhoeher/opentodolist#47]
Lot’s of things I have to do once a year.  Since the interval is so big, these are the things I forget the most. So please add a possibility to repeat a todo once every year!

**Comment by mhoeher** [comment]
As you wish :wink: 

I created an MR over at GitLab, see [here](https://gitlab.com/rpdev/opentodolist/-/pipelines/304346364).

You should be able to download builds for most platforms from the appropriate jobs of that build pipeline. The change will be part of the next release (due beginning of June).

Enjoy!

PS: If you download and try the feature before the next release, I'd be glad if you provide some feedback if this works as you expected. Thanks!

**Comment by Krit1960** [comment]
Wow! That is a quick action. Thanks a lot! As I am kind a new to GitHub I am not sure how to test it. If I understand correctly I could test a snap on Linux?

**Comment by mhoeher** [comment]
Usually, a build pipeline creates "installers" for various operating systems and platforms, which can be downloaded from the build jobs in such a pipeline. If you are using the OpenTodoList snap, you can either switch to the "edge" channel (which I wouldn't necessarily recommend, except you like surprises :wink:) or to the beta one (from time to time, I make a beta build with preliminary features available).

I just made the latest build available to the beta channel, so you could switch to it by running the following command:

```bash
snap refresh opentodolist --channel=beta
```

If you - after the next release is out - want to switch back to stable, simply run

```bash
snap refresh opentodolist --channel=stable
```

**Comment by Krit1960** [comment]
Thanks, Martin.
I really appreciate it that you are so helpfull and responsive.

That said: I do like OpenTodoList a lot, the Schedule view especially is very clear. I am looking for a replacement for my Apple-only favourite: Things and OpenTodoList might be a winner. There might be not as much functionality (yet) as in the other apps I have used but I prefer it above MS Todo (ugly!) and some paid apps.

Kind regards

Arno

Op 18-5-2021 16:08:18, Martin Höher ***@***.***> schreef:
Usually, a build pipeline creates "installers" for various operating systems and platforms, which can be downloaded from the build jobs in such a pipeline. If you are using the OpenTodoList snap, you can either switch to the "edge" channel (which I wouldn't necessarily recommend, except you like surprises 😉) or to the beta one (from time to time, I make a beta build with preliminary features available).
I just made the latest build available to the beta channel, so you could switch to it by running the following command:
snap refresh opentodolist --channel=beta
If you - after the next release is out - want to switch back to stable, simply run
snap refresh opentodolist --channel=stable

**Comment by mhoeher** [comment]
Thanks for these kind words :smile: 

Yes, OpenTodoList is a pure hobby project of mine - so it surely cannot compete with "professional" apps or also larger Open Source ones. But I am glad if its found to be useful, nevertheless :wink: 

If you miss any features, feel free to file another issue (either here or ideally over on [GitLab](https://gitlab.com/rpdev/opentodolist), where the app is actually developed). I cannot promise that every request will be handled so quickly (that usually depends on the complexity of a task, some are rather trivial to implement, other, well, require some thinking), but I'm generally open to any idea that might improve the usability of the app.

**Comment by Krit1960** [comment]
Hi Martin,



Seems to work fine! 

I'll dive in to OpenTodoList and will post requests on Github. I have been working in softwaredevelopment for over 20 years so I now I do not have to expect that everything I would like can be accomplished in short time or at all.

If there are things I can do to help, (not programming, but documenting, translating or testing) please let me know.

Reading your name, corresponding in German would be ok too. 



--

Met vriendelijke groet,



Arno Verhoeven




  ***@***.***

***@***.***

 Threema/Signal









---- Op di, 18 mei 2021 16:05:32 +0200 Martin Höher ***@***.***> schreef ----




Usually, a build pipeline creates "installers" for various operating systems and platforms, which can be downloaded from the build jobs in such a pipeline. If you are using the OpenTodoList snap, you can either switch to the "edge" channel (which I wouldn't necessarily recommend, except you like surprises 😉) or to the beta one (from time to time, I make a beta build with preliminary features available).

I just made the latest build available to the beta channel, so you could switch to it by running the following command:

snap refresh opentodolist --channel=beta


If you - after the next release is out - want to switch back to stable, simply run

snap refresh opentodolist --channel=stable

**Comment by mhoeher** [comment]
Great, thanks for the feedback! So I'll consider this issue as done :wink: 

And thanks for offering your help. Currently, I think most of the work is related to development tasks. But if you like, you can help translating the app over on [POEditor](https://poeditor.com/join/project?hash=ztvOymGNxn).
