### ISSUE TITLE
Recurring tasks at x weeks or months 

### ISSUE THREAD

**Issue by Krit1960** [mhoeher/opentodolist#48]
It would be nice if tasks could be repeated every x weeks or x months. Like you already implemented with days.

**Comment by mhoeher** [comment]
Shouldn't be a big deal to implement :wink: 

I've created an [issue over on GitLab](https://gitlab.com/rpdev/opentodolist/-/issues/447) for the implementation. Maybe I can get this into the next release as well.

**Comment by mhoeher** [comment]
Okay, wasn't a big deal, indeed.

I implemented that feature, you can download builds from [this pipeline](https://gitlab.com/rpdev/opentodolist/-/pipelines/306149647). In addition, I made a new version available via `snap` on the beta channel.

**Comment by Krit1960** [comment]
Hi Martin,



I'm impressed. It seems to work ok. Not thouroghly tested but I have checked x weeks and months with fixed date and date coupled to date of completion.

One remark though: You should check the text:







This is also for x weeks


--

Met vriendelijke groet,



Arno Verhoeven




  ***@***.***

***@***.***

 Threema/Signal









---- Op do, 20 mei 2021 10:44:25 +0200 Martin Höher ***@***.***> schreef ----




Okay, wasn't a big deal, indeed.

I implemented that feature, you can download builds from https://gitlab.com/rpdev/opentodolist/-/pipelines/306149647. In addition, I made a new version available via snap on the beta channel.

**Comment by mhoeher** [comment]
Good to hear it's working generally :wink:

Did you include an image/screenshot to show an issue in the user interface? It seems it did not make it to GitHub :open_mouth:

**Comment by mhoeher** [comment]
Closing this one - the feature is available and part of the most recent release of the app. If there's anything to improve, let me know (ideally, by creating a new issue :wink:).
