### ISSUE TITLE
Question: macOS version for non-M1 Macs?

### ISSUE THREAD

**Issue by fthommen** [mhoeher/opentodolist#49]
The OpenToDoList in the Apple Appstore is only for M1 Macs.  Since most of us probably still have non-M1 hardware :-) : Is there also a version for Intel processors available somewhere?

**Comment by mhoeher** [comment]
Yeah, I shortly looked into distributing the app via the Appstore but ran into some issues and then gave up :sweat_smile: 

The version currently listed there is in fact the iPhon/iPad version (which runs unmodified on M1 hardware).

Currently, you can get the native desktop app for macOS by downloading a DMG file directly from the app releases here on GitHub. For example, you can download the file `OpenTodoList.dmg` from the [3.34](https://github.com/mhoeher/opentodolist/releases/tag/3.34.0) release to get the latest greatest version. These "standalone" versions have an update check, so you at least will get a notification that a new release is available.

In addition, I also have [an issue to look into the upload to the Appstore](https://gitlab.com/rpdev/opentodolist/-/issues/354) (which is actually scheduled for the next release, but I don't know if I'll manage to get it in as the release is already due beginning on June).

**Comment by fthommen** [comment]
I downloaded the app and it works just fine.  Thanks a lot for your quick response.

**Comment by mhoeher** [comment]
Okay, good to know :wink: Thanks!

Keep an eye on the release announcements - eventually, installation should be possible via the Appstore as well.

**Comment by fthommen** [comment]
I will.  Thanks for the heads up
