### ISSUE TITLE
Feature request: Push notifications (iOS)

### ISSUE THREAD

**Issue by devops-42** [mhoeher/opentodolist#51]
Hi @mhoeher 

at first thanks for your nice app.

Do you plan to implement push notifications to get a reminder if a task has reached its due date (and time)?

Cheers!

**Comment by mhoeher** [comment]
Hi @devops-42,

thanks for raising this request. The answer to your questions is kind of: Yes and no :wink: 

First of all: The app will probably never support *push notifications*. Such notifications rely on external services that send a message to your device so the notification gets shown. However, this is completely against the design philosophy of the app (which basically uses a *distributed* approach, where you can let the app store your information on arbitrary storage locations, but other than that, no external communication takes place).

However, I definitely plan to introduce reminders for items (although this is a story which unfortunately takes a bit longer). To shed some light on this:

- On desktop systems, this is not a problem at all - the app can continue to run in the background there without issues and showing notifications there would be quite easy.
- On mobile devices, the story gets more interesting:
  - On Android, there are background services, which pretty much allow a similar set up as on a desktop system. However, getting this up and running reliably also took some time. But this one is done.
  - What currently is outstanding is - and this is unfortunately for the platform you ask for - iOS. There is an open task (see [this issue over on GitLab](https://gitlab.com/rpdev/opentodolist/-/issues/369) which I need to get done. As soon as this is the case, the app would be *regularly called also in the background* (which is kind of similar to what would happen on the other platforms), which in the first step will allow it to sync data in the background.

My plan is to finish that last task and afterwards look into implementing [this issue](https://gitlab.com/rpdev/opentodolist/-/issues/265) which - I think - is pretty much what you asked for. This would also include showing local notifications to remind you of upcoming things to be done.

Sorry for the long text, just wanted to make clear what's going on (which might not be necessarily easy to trace as most users raise their requests here on GitHub while the app is actually developed over on GitLab and not all issues might have proper cross references to each other). If you have further questions (or ideas) then let me know!

**Comment by devops-42** [comment]
Hi @mhoeher 

thanks for the detailed information. I'm looking forward to the next releases. 

Cheers
