### ISSUE TITLE
Is the theming alright.

### ISSUE THREAD

**Issue by asisnil** [mhoeher/opentodolist#52]
So I am using Manjaro gnome with kvantum theme matcha.
the app looks like this.
![Screenshot-20210730122938-1394x767](https://user-images.githubusercontent.com/46134036/127610832-dfeb37f4-52f1-4d39-b068-ffd73f54012e.png)
The snap,flatpak,appimage,aur all versions looks like this.
I don't know if it is normal.
The android version looks right and if I remember correctly the desktop version looked alright too.
Thank you.

**Comment by mhoeher** [comment]
Interesting. This looks definitely wrong. Could you please try to provide the following information:

- If you start the app from a terminal (e.g. via `flatpak run net.rpdev.OpenTodoList`), does it  print something suspicious/unusual (there'll be a lot of lines being printed, but most should be usual business).
- Could you please check if the environment variable `QT_QUICK_CONTROLS_STYLE` is set? If so, this will override the implicit default of the app. From the rendering, it looks like the app could be using a different style than the Material one - however, as the app was not designed to be usable for these, this could possibly result in such a broken rendering.
- Last but not least, the usual suspects: Does restarting the app (use `Ctrl+Q` to terminate it and then start again) or rebooting your entire system change anything? Are your installed packages up to date?

Thanks!

**Comment by asisnil** [comment]
Thanks man.
After  quitting the app with ctrl+q and then uninstalling kvantum, the app was fixed.
It maybe kvantum problem.

**Comment by mhoeher** [comment]
Thanks for the feedback - and interesting. Did you experience similar issues with other apps as well?

**Comment by asisnil** [comment]
No, okular(flatpak) was alright if I remember correctly.
