### ISSUE TITLE
sort todo items by incomplete first

### ISSUE THREAD

**Issue by mortee** [mhoeher/opentodolist#58]
Found this app for nextcloud-synced/shared todo/grocery list app, and so far seems to be the best candidate.

However, after a few hours of tinkering around, I found something quite inconvenient: there seems to be no way to automatically sort todo items so that those completed automatically go to the bottom; or even, simply a separate category like "to do" - separator - "done". 

I guess in most cases, one would rather focus on the outstanding tasks, be it a simple grocery list or a software project. 

Let me know if I'm missing something...

**Comment by mhoeher** [comment]
Hi @mortee,

the current approach is like this: There is a function to toggle between showing completed todos (or tasks), like in the following screenshot.

![Screenshot_20211210_081113](https://user-images.githubusercontent.com/1911135/145532631-6c505810-5d87-42ca-b780-0e48f0c60e8c.png)

The completed todos/tasks remain where they are. With this button, you just adjust the filtering, so they won't be shown anymore.

Does this help in your case?

**Comment by mortee** [comment]
Hi @mhoeher, yeah, in the meantime I discovered that toggle. However, my primary goal being to use the app as a shared grocery list and film watch list, it's not ideal that I either can't see the completed items, or they are interspersed among the outstanding ones. Of course, if this is impossible at the moment for some reason, I understand, but this is the only thing that currently keeps me from switchig over from a proprietary provider with their own hosting (which I even need to hack with VPN because of service area restrictions) to OTDL with my own nextcloud hosting.

**Comment by mhoeher** [comment]
Hi @mortee,

I see. Well, I guess it should be doable to get to what you want. What I could imagine:

- OpenTodoList has a "sorting" functionality. The default is "manual" sorting, but there are  other options as well, e.g. sort by title or creation date.
- What I could easily do: Add an additional sort option like "Keep completed items at the end of the list". This should actually provide what you want to achive.

I'll try to implement something this evening - it shouldn't be a big deal. Will update you here.

**Comment by mhoeher** [comment]
For your reference: [I created an issue over at GitLab](https://gitlab.com/rpdev/opentodolist/-/issues/485), which will be used for implementation.

**Comment by mortee** [comment]
@mhoeher, I believe that was my original suggestion. A visual separator between the two groups - when that sort option is selected - would be a nice touch, but ultimately not too important. I'm glad you're open to implementing this - I'm sure it mustn't be a really thorough change altogether.

For the record, here's how my currently used app looks like:
![Screenshot_20211214-210447](https://user-images.githubusercontent.com/338540/146071565-76b3f441-3dde-467e-9160-7fb926425634.jpg)

**Comment by mhoeher** [comment]
Hi @mortee,

thanks for sharing the screenshot. I guess, introducing this kind of extra functionality eventually might be a nice thing :wink: 

For now, I just added an option to group done/undone items. If you like, you can give it a try. You can find builds of a new version in the jobs of [this CI/CD pipeline](https://gitlab.com/rpdev/opentodolist/-/pipelines/429687400). There are currently issues with both the Snap and iOS builds (these are, however, not related to the changes but in the build environment itself...).

From the screenshot, I guess you are using Android, so you might want to try the Android ARM 64bit build: https://gitlab.com/rpdev/opentodolist/-/jobs/1885460303/artifacts/file/build-android/OpenTodoList-arm64-v8a-3.38.0-14-g711aedb0-aligned.apk

The grouping is off by default. To enable it, click/tap the former "visibility" toggle. This will now show a menu which let's you toggle between showing/hiding done items as well as grouping of done/undone items.

**Comment by mortee** [comment]
This is great, I'll give it a shot a bit later!

**Comment by mortee** [comment]
Okay, checked it out, this is fair enough for my purposes. Thanks for the quick fix!

Just to make it a bit more intuitive: First, the usage of terms "completed" and "done" should be consistent, especially within a single menu. Also, the "group" item should be disabled when completed items are hidden, as it makes no sense at all in that case. Honestly, I would simply call the second menuitem "show at the bottom", only enabling it when the first is checked. 

And one tiny, unrelated thing which made me mad with my old app, and unfortunately OTDL works the same way too: adding a todo item closes the keyboard, so when I'm entering a whole list of items to do/buy, I have to click in the text area again and again and again, for no reason. Is there a way to keep the keyboard open after adding an item?

**Comment by mhoeher** [comment]
Hi @mortee,

thanks for the feedback, I'll try to incorporate it!

Regarding the keyboard thing: What you can do is use the little "plus" icon next to the input box. This should usually keep the keyboard open.

I think I tried to "convince" mobile OSes to keep the keyboard open when using the enter/done key on the keyboard itself, but unfortunately, this was not quite successful. However, using the "plus" icon instead should work.

**Comment by mortee** [comment]
Thanks for the tip, the + icon works indeed!

**Comment by mortee** [comment]
Side note: what's the real purpose of the "Edit List" menuitem? Apparently, that just puts the pen icons on the library rows, doesn't affect the functionality otherwise. Couldn't those icons be shown just constantly?

**Comment by mortee** [comment]
Sorry for using this thread to post suggestions. Advise me otherwise, if preferred. (I thought I wouldn't open separate tickets here, since you're using gitlab for tracking anyway.)

How do I explicitely delete a library both locally and on the server? (I know I can just delete the lib folder _on_ the server, but I mean from within the app)

**Comment by mortee** [comment]
Oh, when the completed items are shown (or, really, in any case) the counter at the top of a todo list should show the number of (outstanding/all).

**Comment by mortee** [comment]
The attach dialog in windows behaves quite strangely: these are the options shown in succession, while I keep clicking the up arrow in the corner.
![image](https://user-images.githubusercontent.com/338540/146437388-b8b50db3-4831-44ed-aa4a-2b3a58befc44.png)
![image](https://user-images.githubusercontent.com/338540/146437407-cbb644ca-e2e3-4e06-a80d-a095ba8beb38.png)
![image](https://user-images.githubusercontent.com/338540/146437420-0e497e48-80e6-4617-ab34-e76a8b94d90e.png)
![image](https://user-images.githubusercontent.com/338540/146437422-69cfcbf8-f875-4905-8ba5-50433c199760.png)

**Comment by mortee** [comment]
Apparently, a TODO library entry ha an option to be exported in markdown. 

First, while it applies to both the title and the notes, the icon for this is besides the notes. It would make more sense to move this to the top row.

Also, why aren't the todo items themselves exported? This pretty much defeats the purpose...

**Comment by mortee** [comment]
Is there a way to import items in any form? Or would I need to transfer my old lists item by item, manually?

**Comment by mhoeher** [comment]
Hi @mortee,

thanks for posting further suggestions and questions, that's definitely welcome (probably also for others who eventually might stumble upon this) 😉 

However, could you please do me a favour and indeed create at least individual issues for suggestions? This helps me keeping track of them (even if you create them here on GitHub).

You also could log in on GitLab - there's a "Login with GitHub" function there - however, only do this if it's okay for you. However, this would have the added benefit for you that you'll receive immediate feedback if somethings going on on the issues you create there 😉 

Thanks!

**Comment by mortee** [comment]
Sure enough, I'll go to gitlab then. Would you mind however giving me a whatsapp or other instant contact? We might be able to filter through such ideas a bit more quickly than committing the discussion to github/lab. Just an idea.

**Comment by mhoeher** [comment]
Do you have an account on Twitter? Then we can connect there and DM. Otherwise, drop me a mail via martin AT rpdev DOT net. 😉

**Comment by mhoeher** [comment]
As the feature is implemented and merged to the development branch (and hence will be part of the next release), I'll go ahead and close this issue here. :wink:
