### ISSUE TITLE
multiple select attache files

### ISSUE THREAD

**Issue by ProNoiser** [mhoeher/opentodolist#59]
Hello!
Please make multiple select attache files into Tasks, Notes etc, and drag'n'drop many files in app windows. Thanks!
Very nice App!

**Comment by mhoeher** [comment]
Hi @ProNoiser,

just to make sure I get you correctly: You want - when you attach files - be able to select multiple files in the file dialog that then are attached?

**Comment by ProNoiser** [comment]
Hi, Martin.

Yes! Exactly this. And also drag and drop files with the mouse from the explorer to the application window. And then I have to open the file attachment window several times. It is very uncomfortable!

And everything else is great. I like! Thanks!

> Hi @ProNoiser,

> just to make sure I get you correctly: You want - when you attach files - be able to select multiple files in the file dialog that then are attached?

**Comment by mhoeher** [comment]
Okay, thanks!

I created two issues over on GitLab (this is where the project is developed). Here you go:

- https://gitlab.com/rpdev/opentodolist/-/issues/521
- https://gitlab.com/rpdev/opentodolist/-/issues/522

I think I'll implement attaching multiple files via the dialog first - I guess that should be rather straightforward to do. Drag and drop from other apps might be a bit harder to get done - I have to check how to do this first.

**Comment by mhoeher** [comment]
Hi @ProNoiser,

took a while, but here you go:

I implemented both, i.e. attaching multiple files as well as drag&drop from the file explorer.

You can download test versions from the artefacts of the jobs in this CI/CD pipeline: https://gitlab.com/rpdev/opentodolist/-/pipelines/566834284

The changes will be part of the next release, which is due end of this month (if everything goes well).
