### ISSUE TITLE
AppImage does not run on Ubuntu GNOME 17.04

### ISSUE THREAD

**Issue by probonopd** [mhoeher/opentodolist#6]
AppImage does not run on ubuntu-gnome-17.04-beta2-desktop-amd64.iso:

```
me@host:~$ '/home/me/Downloads/OpenTodoList-stable.AppImage' 
/home/me/Downloads/OpenTodoList-stable.AppImage: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
```

This could probably be solved by bundling libpcre.

**Comment by mhoeher** [comment]
Thanks for reporting. I will look into this.

For the records: I created a linked issue on GitLab (https://gitlab.com/rpdev/opentodolist/issues/108) as the project is developed mainly there ;-)

**Comment by hyOzd** [comment]
@mhoeher Same error in Mint 18.1 (based on ubuntu 16.04).

**Comment by mhoeher** [comment]
Hi @probonopd and @hyOzd,

sorry for the late reply. In the scope of another issue I added building the AppImage based on Ubuntu Trusty. Could you please try with this AppImage: 

http://rpdev.net/public/appimages/linux/x86_64/OpenTodoList-x86_64.AppImage

As mentioned, it is built in CI using Ubuntu Trusty and compiled against Qt 5.9.1. I tested it on a Fedora 26 installation and there the app runs fine.

**Comment by probonopd** [comment]
Runs well on openSUSE LEAP 42.3. Any chance this will appear on GitHub Releases?

**Comment by hyOzd** [comment]
Unfortunately I can't access my mint 18 machine at the moment. But I can confirm that it runs on mint 17.3 fine.

**Comment by mhoeher** [comment]
Thanks for testing! I guess this is yet another proof that Fedora is not a good platform to build AppImages on ;-)

@probonopd: Interesting idea, I will look into this. For your `linuxdeployqt` tool I see you use your `uploadtool`. My app is hosted on GitLab, hence I guess I cannot reuse this script without modifications, right?

**Comment by probonopd** [comment]
@mhoeher true, `uploadtool` is written specifically for GitHub Releases and Travis CI. But I guess something similar could be done for GitLab.

CentOS 6.x (as one example of a Red Hat-like distribution) has been used with success for building AppImages.

**Comment by mhoeher** [comment]
@probonopd Okay, I will look into it. Maybe it is also just a matter of setting some environment variables to push to GitHub from within a GitLab CI ;-)

Regarding the choice of host OS: I don't care too much. If Ubuntu is working fine as a base, I'll happily use it (in the end I try to get as much work automated via CIs as possible and thanks to Docker there are plenty of host OSes available :-) ).

**Comment by probonopd** [comment]
About the OS, the age is more important than what OS it is. Ubuntu trusty 14.04 should be fine at this point, too.

**Comment by mhoeher** [comment]
FYI: I created an issue in GitLab to track the upload implementation - https://gitlab.com/rpdev/opentodolist/issues/116.

Closing this issue for now as the newly build AppImages seem to work ;-)
