### ISSUE TITLE
Trying to link to my own private Baïkal CalDav server and nothing happens

### ISSUE THREAD

**Issue by therealrobster** [mhoeher/opentodolist#61]
Hi there,

I load up opentodolist and click on Accounts, then + button.
I then choose Webdav and enter all the settings (address, user, password, name).
Then press the OK button and nothing happens.
No error, no progress.  Nothing.

Are there at least logs or similar I can check?

Thank you

**Comment by mhoeher** [comment]
Hi @therealrobster,

OpenTodoList does not use CalDAV as a backend but instead stores its data in a file system. Currently, the built-in sync supports WebDAV as a transport, with Dropbox currently being integrated as well.

CalDAV support is out of scope of this app - sorry :wink:

Please let me know if you need further help on this.

**Comment by therealrobster** [comment]
ahhh, ok.  Thank you so much.  The struggle continues :-)  I'll find that proper caldav desktop client one day I'm sure.  Thanks for your time and response.
