### ISSUE TITLE
Is there support for interfacing with Tasks app in Nextcloud?

### ISSUE THREAD

**Issue by rtevans01** [mhoeher/opentodolist#65]
Title pretty much says it all. It appears to me OpenTodoList makes its own Nextcloud folder to sync with and that's it.

**Comment by mhoeher** [comment]
Hi @rtevans01,

no, there is no way to interface with NextClouds Tasks app. NC Tasks is storing information in the calendar (i.e. it uses CalDAV as exchange protocol). OpenTodoList on the other side uses plain files (which are synchronized via e.g. WebDAV).

It was a deliberate decision not to built OpenTodoList based on CalDAV. Sub-Tasks support in CalDAV is - unfortunately - not standardized and basically each server/client tends to store the information in slightly different formats. For this reason, OpenTodoList uses files (bonus here is, that the sync in theory can be done via any file exchange service - currently, support for e.g. Dropbox is under way).

Let me know if you need further information!

**Comment by rtevans01** [comment]
Hi. Thanks for the response. I just thought I'd ask since Nextcloud Tasks can sync with the Tasks.org app through the DAVx app.
Speaking of which, can the Task.org app sync with OpenTodoList through the folder it assigns itself on a Nextcloud server?

**Comment by mhoeher** [comment]
I don't know. From the description on their website, I would guess Tasks.org is also built on CalDAV and hence, the answer is probably "no", but I have not verified this.

If you'd find out more, I'd be interested, though :wink:
