### ISSUE TITLE
Global schedule view

### ISSUE THREAD

**Issue by hynow** [mhoeher/opentodolist#68]
A schedule view that merges the schedules of all libraries would be very helpful!

**Comment by mhoeher** [comment]
I agree 😉 

There is a similar (well, kind of) request on GitLab: https://gitlab.com/rpdev/opentodolist/-/issues/239

That one asks for a kind of unified view of todo list across libraries. This would require some modifications/enhancements in the business logic and for GUI voodoo but should be doable. In the same direction, I think such a global schedule view would definitely be possible.

I created another issue there to handle your request: https://gitlab.com/rpdev/opentodolist/-/issues/532

Feel free to provide further ideas related to this feature either here or on GitLab!

**Comment by mhoeher** [comment]
As this is implemented and part of the last release, I'm going ahead and close this one. Thanks again for raising and have a lot of fun the the new feature!
