### ISSUE TITLE
Request: Show some pictures in the readme

### ISSUE THREAD

**Issue by lquenti** [mhoeher/opentodolist#73]
Hey, sorry for the nontechnical issue but whenever I decide on some software I compare it via screenshots, as they are more information dense than a description.

Id would be great if you'd have some screenshots for all platforms!

**Comment by mhoeher** [comment]
Hi @lquenti,

no reason to be be sorry. Your request is very valid indeed. And in fact, we have other places (like the Google Play Store) where we have screenshots but these are horribly outdated.

I'll try to  improve the README for the next release.

Here's the appropriate GitLab issue: https://gitlab.com/rpdev/opentodolist/-/issues/545

**Comment by mhoeher** [comment]
Yes, it took a while but.. this is done (finally!). Hence, closing this ticket 😉
