### ISSUE TITLE
Markdown syntax highlighting and rendering issues

### ISSUE THREAD

**Issue by ZhangTianrong** [mhoeher/opentodolist#76]
There seems to be some issues with the note editor. See the following example which exposes a few of them:
![image](https://user-images.githubusercontent.com/20651728/187719541-6e4c26b9-2d59-4390-a2ab-279bfda1ff83.png)
![image](https://user-images.githubusercontent.com/20651728/187720155-c0c99d3a-9b0c-4dc8-ad58-1701fc5ff387.png)

+ It seems that ":" has triggered some highlighting scheme by mistake. AFAIK, ":" isn't a special character in markdown unless it's in a table to specify aliignment
+ An email address at the end of a line seems to cause the next bullet point to be colored green
+ Nested list seems to be limited to 2 layers only

By the way, is there a way to exit the editing mode and see the rendering results without existing the current page and re-enter it?

**Comment by mhoeher** [comment]
Closing, as you've opened another issue about the same topic on GitLab: https://gitlab.com/rpdev/opentodolist/-/issues/575
