### ISSUE TITLE
Return button unresponsive if the note editor is active in a nested item

### ISSUE THREAD

**Issue by ZhangTianrong** [mhoeher/opentodolist#77]
See the following GIF for details:
![GIF](https://user-images.githubusercontent.com/20651728/187722381-922fbca2-7c95-434b-a236-360ae1bb736a.gif)

**Comment by mhoeher** [comment]
Closing this one, as you've also opened an issue over on GitLab: https://gitlab.com/rpdev/opentodolist/-/issues/576
