### ISSUE TITLE
Request : location of libraries in the file system, and related operations

### ISSUE THREAD

**Issue by CesareB66** [mhoeher/opentodolist#78]
Hello,
it would be interesting to be able to view the physical location of the created libraries (in the case of filesystem-based libraries), and, in addition, the possibility of performing some basic operations (copy, move) of the same libraries in other locations, including cloud locations, and viceversa.

**Comment by mhoeher** [comment]
Hi @CesareB66,

thanks for opening this request.

Regarding the first part: I think it makes sense making the path information available somehow. I'll put this on the agenda for one of the next releases :wink: 

Regarding the latter part: This is out of scope of the app. If you use "libraries in folders", than you can copy them around on your own (e.g. for backup purposes). If you want to have a library which is synchronized between several devices, OpenTodoList supports several protocols (currently WebDAV and there in particular sync against NextCloud and ownCloud instances as well as Dropbox). These are the way to go for having a library on multiple devices.

**Comment by mhoeher** [comment]
Short update: For the first part, I raised an issue over on GitLab to implement this - see https://gitlab.com/rpdev/opentodolist/-/issues/581.

**Comment by mhoeher** [comment]
As https://gitlab.com/rpdev/opentodolist/-/issues/581 is implemented meanwhile (the change will be part of the next release which will be out around end of March/beginning of April), I'll close this issue. If you have further input/ideas/..., feel free to add it and reopen this issue 😉
