### ISSUE TITLE
Clicking the Settings Close button does nothing on Win11

### ISSUE THREAD

**Issue by nagulv** [mhoeher/opentodolist#80]
As in title. Once in the Settings page, the "Close" button does nothing. The settings seem to be applied as soon as they are changed, so I assume the Close button should take you back to the previous page. However, this does not work, there is no discernible change on clicking the Close button. The only way to get back is to click the back arrow at the left top of the app.

**Comment by mhoeher** [comment]
Hi @nagulv,

thanks for reporting! Yes, you are right. This is an artefact of some redesign in the past. I raised a tracking issue over on [GitLab](https://gitlab.com/rpdev/opentodolist/-/issues/609) to track development of a fix. I guess I'll simply remove the button (the main way of closing/going back in the page stack is the arrow back button in the tool bar).

**Comment by mhoeher** [comment]
Short update: I removed the button and merged that change to the development branch. The fix will be part of the next release 😉 Hence, closing this issue for now.

Thanks again for reporting!
