### ISSUE TITLE
OpenTodoList Won't Launch on EndeavourOS

### ISSUE THREAD

**Issue by LinuxAndCoffee** [mhoeher/opentodolist#83]
I just installed this via "yay -S opentodolist" and when I try to launch it using "OpenTodoList" from the command line I get the following error:

OpenTodoList: error while loading shared libraries: libqlmdb-qt6.so.1.2.1: cannot open shared object file: No such file or directory

The package in the AUR is version opentodolist 3.43.0-1.

**Comment by mhoeher** [comment]
Hi @LinuxAndCoffee,

thanks for raising this request. And sorry, I also saw your comment on AUR but didn't find the time looking into this yet (had a busy week so far).

Regarding the issue you see: That library is a dependency of OpenTodoList that is actually build as part of the app and hence also should get installed alongside it. However, for some reason it seems the app does not "find" it when started or the library isn't properly installed. I can confirm this behaviour with Arch Linux.

I created an issue to fix this over on GitLab: https://gitlab.com/rpdev/opentodolist/-/issues/614

In the meantime, if possible, you could try to use the app by downloading the AppImage or install it from Flatpak. Sorry for the inconvenience :-(

**Comment by mhoeher** [comment]
The issue has been fixed and a new PKGBUILD file been uploaded already. Hence, closing this ticket 😉
