### ISSUE TITLE
It does not open in Linux Arch, due to an error  libqlmdb-qt6.so.1.2.1

### ISSUE THREAD

**Issue by l337quez** [mhoeher/opentodolist#84]
I use Gnu linux Arch and I installed the application by AUR but it gives me the following error.

OpenTodoList: error while loading shared libraries: libqlmdb-qt6.so.1.2.1: cannot open shared object file: No such file or directory

**Comment by mhoeher** [comment]
Hi @l337quez,

thanks for raising this request.

This is a known issue - it basically is the same as #83. Actually, I wanted to have this fixed already, but the last few weeks were really busy plus I got a bad cold on top, so sorry for the delays and not having rolled out a fix yet.

I'll close this issue in favour of #83; feel free to subscribe to that one instead. I hope to fix the core issue this evening and then start the release of the new version, so the fix should get available latest in the next few days.

**Comment by l337quez** [comment]
Thank you very much, I like this app, I would like it to have integration with mega
