### ISSUE TITLE
View note icon

### ISSUE THREAD

**Issue by Docmine17** [mhoeher/opentodolist#85]
This option to view the note is with the download icon instead of the view Icon

![Captura de tela de 2023-04-24 10-33-53](https://user-images.githubusercontent.com/67164552/234012424-2584dae5-6059-4dc0-b977-ece227cbaab2.png)

![Captura de tela de 2023-04-24 10-28-42](https://user-images.githubusercontent.com/67164552/234010829-7874dfd1-ed09-4d11-9ce1-2987a5007994.png)

View icon:
![image](https://user-images.githubusercontent.com/67164552/234013150-3497f376-9742-4376-9a5f-292782f6471f.png)

Or just a check
✅ ✓

**Comment by mhoeher** [comment]
Hi @Docmine17,

thanks for the heads up. I've been made aware of this in the past already, however, without opening an issue. So, seems like I successfully procrastinated regarding this issue 😉 

I created an issue over on GitLab to fix this: https://gitlab.com/rpdev/opentodolist/-/issues/618

Hope that it'll make it into the next release.

**Comment by mhoeher** [comment]
Short update: The fix is implemented and currently being merged to the development branch. Hence, it'll be part of the next release (due end of June).

Hence, closing the issue here.

Thanks again for the heads up!
