### ISSUE TITLE
feature anfrage (wartungstermine)

### ISSUE THREAD

**Issue by real-easy** [mhoeher/opentodolist#87]
hallo, 

ich schreibe mal auf deutsch, sonnst wäre es vermutlich nicht einfach zu deuten. (gruß von thüringen nach sachsen)

ich mag die todo-liste wirklich sehr und nutze sie täglich.
den größen vorteil sehe ich beim selbst hosten und der veknüpfung der verschiedenen platformen.

um das teil noch besser zu machen würde ich mir wiederkehrende aufgaben nach intervallen oder terminen wünschen.

z.b. jeden montag die blumen gießen oder 1x im monat  den druck der heizung kontrollieren.
der folge-termin sollte dann im intervall oder nach datum automatisch generiert werden wenn der aktuelle task abgeschlossen wurde.
ähnlich wie es bei den outlook aufgaben möglich ist.

also falls es die zeit zu lässt und du ein feature zum erweitern brauchst wär das mein vorschlag.
danke für die bisher geleistete mühe
beste grüße
easy

**Comment by mhoeher** [comment]
Hallo @real-easy,

danke für dein Feedback und viele Grüße zurück nach Thüringen 😉 

Bzgl. deiner Anregung: Tatsächlich kann die OpenTodoList solche sich wiederholenden Aufgaben bereits. Leider gibts noch keine Dokumentation, daher muss man sich noch durch die Symbole "Tasten", also hier in Kurzform:

1. Du kannst ein beliebiges Item (Notiz, Todo Liste, Todo oder Bild) öffnen.
2. Oben in der Symbolleiste das Symbol mit dem Kalender benutzen. Falls es nicht dargestellt wird (z.B. auf dem Handy im Portraitmodus) einfach auf die drei Punkte oben rechts tippen und den Punkt "Set Due Date" auswählen.
3. Es sollte sich ein Kalender öffnen, in dem du ein Datum auswählen kannst. Dieses dann mit "Ok" bestätigen.
4. Jetzt sollte in dem Item - relativ weit oben, in der Regel über den Notizbereich - ein Bereich auftauchen, in dem das gewählte Datum auftaucht. Direkt darunter sollten sich zwei Schriftzüge finden: "No recurrence pattern set" sowie "Recurs indefinitely".
  1. Durch das Klicken des Symbols in der Zeile "No recurrence pattern set" öffnet sich ein Dialog, in dem ein Wiederholungsmuster festgelegt werden kann. Derzeit unterstützt die App Nie, täglich, wöchentlich, monatlich, jährlich sowie alle N Tage, N Wochen oder N Monate.
  2. In der Zeile darunter kann dann ein Enddatum gewählt werden. Wenn keines gewählt wurde, dann wird sich das Item "unendlich" wiederholen. Ansonsten wiederholt es sich bis zum gewählten Termin und wird danach als komplettiert markiert.

Es gibt auch noch einen offenen Feature Request, um diese Wiederholungen etwas aufzupeppen: https://gitlab.com/rpdev/opentodolist/-/issues/515

Im Endeffekt geht es darum, dass - wenn man z.B. eine Todo Liste mit Todos hat und die Todo Liste selbst als gemacht markiert, diese sich dann - durch Wiederholung - auf einen neuen Termin setzt, die enthaltenen Todos ebenfalls wieder als "Offen" angezeigt werden. Derzeit bleiben enthaltene Todos einfach als erledigt markiert (gleiches Spiel bei Todos mit Unteraufgaben).

Ich hoffe das hilft dir erstmal weiter. Wenn du noch andere Vorschläge hast oder das Feature nicht dem entspricht, was du brauchst, lass es mich gerne wissen 😉 

Viele Grüße aus Dresden!

**Comment by real-easy** [comment]
hallo martin, 

ich wuste doch das dein tool super ist. 
die funktion hatte ich selbst noch nicht gefunden. 
ein lesen der doku habe ich ehrlich gesagt auch noch nicht in betracht gezogen. 
das sollte ich in zukunft wohl mal öfter in betracht ziehen. 

wen ich es richtig verstanden habe setzt man den termin nicht auf den task sonder auf die ganze liste. 
ist diese ein mal erledigt worden aktiviert sich die ganze liste nach dem muster welches mit gegeben wurde. 

also habe ich mir mal eine neue bibliothek erstellt in der nun die listen mit den wartungsaufgaben erstellt werden. 
das kling für mich genau wie das was ich gesucht habe. da zu einer wartungsaugabe meist mehrer tasks gehören. 
(z.b. papierkob leeren, dann backup, dann updates) 

das andere feature request (515) vom stefan kann ich vollkommen nachvollziehen, dem würde ich mich direkt anschließen. 
da manche tasks zeit benötigen oder die famile zwischen durch andere ideen hat ist es hilfreich die tasks einzeln abzuhaken. 
wenn die liste dann durch ist sollte das zum nächsten termin dann wieder leer von vorne beginnen. 
ob das, wie er schreibt, optional pro task sein muss glaube ich eher nicht. 

evtl. würde ich noch einen schritt weiter gehen wollen. 
so das sich die ganze liste auch direkt selbst als erledigt markiert wenn alle tasks erledigt sind. 

was mir gerade beim test mit einer notiz noch aufgefallen ist... 
wenn man die notiz als erledigt markiert wird sie nach dem muster auf das nächste datum verschoben, soweit ok. 
klickt man nun aber wiederholt auf das symbol, wird das datum nochmals weiter verschoben. 
also nicht relativ zum aktuellem datum an dem man die aufgabe erledigt hat, sondern relativ zum soll datum zu dem die aufgabe erledigt werden sollte. 
(so gesehen werden meine blumen nun erst wieder am 29.mai gegossen, ich denke das werden sie mir übel nehmen.) 

ist das so gewollt ? 
ich würde es bevozugen wenn das aktuelle datum als referenz genommen wird, egal wie oft man klickt. 
da es vorkommen kann das manche wartungsaufgaben schon vor dem termin erledigt werden. (z.b. wegen defekt und austausch) 
würde man die liste nun als erledigt markieren verschiebt sich die liste nicht um das mit gegebene muster, sondern um das muster + anzahl der übrigen tage. (ich hoffe das ist halbswegs verständlich ausgedrückt.) 

außerdem würde ein versehentlicher doppelklick nichts ducheinander bringen. 

ich arbeite mich noch etwas ein, und teste mal alle buttons, burger und punkte menus. 


ich danke dir für die tolle arbeit und die info. 

beste grüße 
enrico 



Von: "Martin Höher" ***@***.***> 
An: "mhoeher/opentodolist" ***@***.***> 
CC: "real-easy" ***@***.***>, "Mention" ***@***.***> 
Gesendet: Montag, 8. Mai 2023 22:05:22 
Betreff: Re: [mhoeher/opentodolist] feature anfrage (wartungstermine) (Issue #87) 





Hallo [ https://github.com/real-easy | @real-easy ] , 

danke für dein Feedback und viele Grüße zurück nach Thüringen 😉 

Bzgl. deiner Anregung: Tatsächlich kann die OpenTodoList solche sich wiederholenden Aufgaben bereits. Leider gibts noch keine Dokumentation, daher muss man sich noch durch die Symbole "Tasten", also hier in Kurzform: 

    1. Du kannst ein beliebiges Item (Notiz, Todo Liste, Todo oder Bild) öffnen. 
    2. Oben in der Symbolleiste das Symbol mit dem Kalender benutzen. Falls es nicht dargestellt wird (z.B. auf dem Handy im Portraitmodus) einfach auf die drei Punkte oben rechts tippen und den Punkt "Set Due Date" auswählen. 
    3. Es sollte sich ein Kalender öffnen, in dem du ein Datum auswählen kannst. Dieses dann mit "Ok" bestätigen. 
    4. Jetzt sollte in dem Item - relativ weit oben, in der Regel über den Notizbereich - ein Bereich auftauchen, in dem das gewählte Datum auftaucht. Direkt darunter sollten sich zwei Schriftzüge finden: "No recurrence pattern set" sowie "Recurs indefinitely". 
    5. Durch das Klicken des Symbols in der Zeile "No recurrence pattern set" öffnet sich ein Dialog, in dem ein Wiederholungsmuster festgelegt werden kann. Derzeit unterstützt die App Nie, täglich, wöchentlich, monatlich, jährlich sowie alle N Tage, N Wochen oder N Monate. 
    6. In der Zeile darunter kann dann ein Enddatum gewählt werden. Wenn keines gewählt wurde, dann wird sich das Item "unendlich" wiederholen. Ansonsten wiederholt es sich bis zum gewählten Termin und wird danach als komplettiert markiert. 


Es gibt auch noch einen offenen Feature Request, um diese Wiederholungen etwas aufzupeppen: [ https://gitlab.com/rpdev/opentodolist/-/issues/515 | https://gitlab.com/rpdev/opentodolist/-/issues/515 ] 

Im Endeffekt geht es darum, dass - wenn man z.B. eine Todo Liste mit Todos hat und die Todo Liste selbst als gemacht markiert, diese sich dann - durch Wiederholung - auf einen neuen Termin setzt, die enthaltenen Todos ebenfalls wieder als "Offen" angezeigt werden. Derzeit bleiben enthaltene Todos einfach als erledigt markiert (gleiches Spiel bei Todos mit Unteraufgaben). 

Ich hoffe das hilft dir erstmal weiter. Wenn du noch andere Vorschläge hast oder das Feature nicht dem entspricht, was du brauchst, lass es mich gerne wissen 😉 

Viele Grüße aus Dresden!

**Comment by mhoeher** [comment]
Hallo @real-easy,

ich gehe mal der Reihe nach durch:

> ein lesen der doku habe ich ehrlich gesagt auch noch nicht in betracht gezogen.

Nur um das klarzustellen: Eine Dokumentation gibt es bisher eben leider nicht :-( Es existiert ein Request, dass eine solche erstellt wird, aber na ja... habe es bisher einfach noch nicht geschafft (und gute Dokumentation zu schreiben kostet definitiv auch Zeit). Von daher... an der Stelle hast du quasi nichts verpasst ;-)

> wen ich es richtig verstanden habe setzt man den termin nicht auf den task sonder auf die ganze liste.
> ist diese ein mal erledigt worden aktiviert sich die ganze liste nach dem muster welches mit gegeben wurde.

Je nachdem, was du machen möchtest. Du kannst ein Datum (und entsprechend wiederkehrende Termine) für fast alle Items in der app anlegen. Der (bewusste) Unterschied zwischen "Todos" und "Unteraufgaben"/"Tasks" ist, dass Zweitere wesentlich einfacher sind und z.B. keine Notizen oder andere Angaben außer ihrem Namen und dem "Done" Zustand haben. Ob du nun also Todo Listen oder Todos als das Item mit dem Zieldatum verwendest hängt also eher davon ab, wie viele Informationen (und auf welcher Ebene) du brauchst.

> das andere feature request (515) vom stefan kann ich vollkommen nachvollziehen, dem würde ich mich direkt anschließen.

Gut, ein weiterer Grund, dass demnächst in der App zu integrieren ;-)

> evtl. würde ich noch einen schritt weiter gehen wollen.
> so das sich die ganze liste auch direkt selbst als erledigt markiert wenn alle tasks erledigt sind.

Wie heißt es so schön... manche sagen so, andere sagen so. Die Idee, ein Item als "Done" zu markieren, sobald alle Unteraufgaben erledigt sind, ist nicht neu - aber eben auch nicht allgemein gültig. Für einige Anwendungsfälle wäre dieses Verhalten gewünscht; wie in deinem Fall, wenn der "Container" in dem deine Aufgaben sind, wirklich nur als "leeres" Behältnis dient, das nichts anderes macht, als die konkreten Aufgaben zu beinhalten.

Aber es gibt eben auch die anderen Fälle. Ein Beispiel: Wenn ich etwa größere Änderungen an der OpenTodoList implementiere, mache ich mir gerne auch mal ein Todo in meiner "Reminder" Liste. In dieses Todo kommen dann - "on the fly" - einzelne Aufgaben, die mir beim Arbeiten an dieser Änderung einfallen, so dass ich sie nicht vergesse. In diesem Fall möchte ich aber definitiv nicht, dass das Todo als erledigt markiert wird, sobald die letzte Unteraufgabe erledigt wurde. Dieser Zustand ("vorerst alles erledigt für dieses Aufgabe") ist eben nur temporär, und wenn ich mit der Entwicklung
 an dem Feature weitermache, kommen meistens noch neue Unteraufgaben dazu, die ich mir vermerken muss.

Was ich mir aber vorstellen könnte: Sobald man als Benutzer das letzte Item in einem Container als erledigt markiert, könnte die OpenTodoList nachfragen - via einem Dialog oder als kurzer "Toast", also so einer schwebenden Mitteilung am Bildschirmrand, mit der man interagieren kann - ob auch das übergeordnete Item als "Done" markiert werden soll. Was denkst du dazu?


> was mir gerade beim test mit einer notiz noch aufgefallen ist...
> wenn man die notiz als erledigt markiert wird sie nach dem muster auf das nächste datum verschoben, soweit ok.
> klickt man nun aber wiederholt auf das symbol, wird das datum nochmals weiter verschoben.
> also nicht relativ zum aktuellem datum an dem man die aufgabe erledigt hat, sondern relativ zum soll datum zu dem die > aufgabe erledigt werden sollte.
> (so gesehen werden meine blumen nun erst wieder am 29.mai gegossen, ich denke das werden sie mir übel nehmen.)
>
> ist das so gewollt ?

Tatsächlich ist das so gewollt. Ich bin hier aber auch für Vorschläge offen. ;-)


> ich würde es bevozugen wenn das aktuelle datum als referenz genommen wird, egal wie oft man klickt.
> da es vorkommen kann das manche wartungsaufgaben schon vor dem termin erledigt werden. (z.b. wegen defekt und 
> austausch)
> würde man die liste nun als erledigt markieren verschiebt sich die liste nicht um das mit gegebene muster, sondern um 
> das muster + anzahl der übrigen tage. (ich hoffe das ist halbswegs verständlich ausgedrückt.)

Tatsächlich gibt es diese Option schon ;-)

Wenn du ein Wiederholungsmuster einstellst gibt es in dem Dialog, in dem das Muster festgelegt wird, auch eine Option (in Englisch "Recur relative to the date when marking as done"). Diese Option ist standardmäßig aus, d.h. ein Item, das sich wöchentlich wiederholt und initial für z.B: Montag eingetragen ist, wird - beim klick auf "Done" - auf die darauffolgende Woche Montag verschoben.

Wenn die besagte Option allerdings aktiviert wird und das Item z.B. schon drei Tage vorher, also am Freitag, geschlossen wird, dann wird es in der darauffolgenden Woche ebenfalls auf den Freitag gelegt.

Auch mit dieser Option würde ein Item - wenn es mehrfach als "Done" markiert wird - immer weiter in die Zukunft geschoben.

Hoffe das bringt noch etwas Klarheit. Viel Spaß noch beim Ausprobieren und bei weiteren Fragen einfach nachhaken!

**Comment by real-easy** [comment]
hallo martin,

danke für die ausfühliche antwort und die zeit die die du dafür geopfert hast.

ich habe das nun ein wenig weiter getestet und auch einiges neues endekt.

wie du schon geschrieben hast ist es auch möglich den aufgaben einer liste ein datum und ein invervall zu verpassen.
wenn das datum/intervall an der aufgabe selbst hängtm, aktiviert sich diese auch wieder selbsständig nach dem abhacken.
(eher wohl wird sie nicht abgehackt dendern direkt auf den neuen termin verschoben).
damit kann man schon gut etwas anfangen.

bei den unteraufgaben gibts kein datum zum mitgeben, das ist aus meiner sicht auch nicht weiter nötig

aber auch hier wäre es wünschenswert wenn sich die unteraufgaben einer aufgabe mit intervall wieder aktivieren würden wenn der termin wieder drann ist, oder wenn die aufgabe auf den neuen termin verschoben wird.
natürlich gerne auch auf nachfrage...
das ist ja generell nur interresant wenn eine liste oder eine aufgabe ein intervall hat. wenn es nur ein termin ohne intervall ist braucht auch nichts wieder aktiviert zu werden.


die geschichte mit dem datum relativ zum eledigt datum hat anscheinen einen kleinen bug.
ich hatte den haken ja gesetzt beim erstellen der wiederholung und es hat nicht wie erwartet funktioniert.
nun habe ich das weiter untersucht und bemerkt das der haken beim ersten erstellen des termins nicht immer mit gespeichert wird.
denn wenn man die den intervall nochmals an sieht ist der haken dann nicht mehr drinn.
daher auch verhält sich der termin dann natürlich wie ohne den haken.

dabei ist mir aufgefallen das auch der intervall beim 1. erneuten öffnen nicht angezeigt wird.
bricht man das fenster ab und schaut den intervall erneut an wird es vom intervall her richtig angezeigt.
öffnet man das fesnter erneut ist der intervall wieder weg, beim nächsten öffen ist er wieder da.
das wechselt sich ab.


der haken für das relative datum wird beim erneuten setzen dann direkt gespeichert.
dann ist die funktion natürlich auch wie erwartet. klasse!

aber auch hier ist es so das beim mehrfachen abhaken am selben tag der termin immer im intervall immer weiter geschoben wird.
ich finde das wiederspricht sich dann mit der beschreibung "relativ zum datum der erledigung".
denn auch wenn man die aufgabe 3x am selben tag erledigt sollte der intervall relativ zur letzen erledigung eingehalten werden.
wenn man das weiss kann man aber sicher damit leben.


ich habe dann bei weiteren test mal eine lokale bibliothek angelegt um übertragungs delays auf den server auszuschließen.
hier ist das verhalten mit der alternierenden anzeige auch so.
anders ist aber das der haken (relatives datum) direkt beim erstellen des termins schon richtig mit gespeichert wird.

üblicher weise habe ich ein konto mit der DAV schnittstelle meines seafile-servers verbunden in dem alle listen und aufgaben liegen.
da ist der zugriff logischer weise langsamer als lokal.
es könnte natürlich auch eine cache einstellung sein die das verhalten beim speichern des hakens beeinflusst.
ich muss mal schauen ob sich da etwas machen lässt.

ich habe übringens immer gewartet bis der ladekreis / wartekringel weg war bevor ich ein neues fenster geöffnet habe.


beim testen ist mir dann aufgefallen das es recht mühsam ist immer das kleine symbol zu treffen um den intervall einzustellen.
(gerade heute habe ich schon 2 tonnen pellets in den keller geschleppt.)
ich benutze hauptsächlich die desktop app (windows).
da wäre es aus meiner sicht eine verbesserung wenn man zum symbol auch noch den text als schaltfläche hätte.
also den text "kein muster gesetzt" direkt anklicken kann um den intervall einzustellen.
da das symbol rechtsbündig ist muss man immer so weit rüber mit der maus. und die menschen sind doch so faul...


so, ich will dich nicht zu lange nerven.
die blumen habe ich heute gegossen, keine gefahr mehr.

beste grüße
aus thüringen

**Comment by mhoeher** [comment]
Hallo @real-easy 

sorry erstmal, die letzten Tage waren etwas stressig, daher bin ich nicht zum Antworten gekommen.

> aber auch hier wäre es wünschenswert wenn sich die unteraufgaben einer aufgabe mit intervall wieder aktivieren würden wenn der termin wieder drann ist, oder wenn die aufgabe auf den neuen termin verschoben wird.

Genau das ist wird mit dem bereits verlinkten Issue kommen, ist also eingetütet 😉 

> das ist ja generell nur interresant wenn eine liste oder eine aufgabe ein intervall hat. wenn es nur ein termin ohne intervall ist braucht auch nichts wieder aktiviert zu werden.

Richtig - dieses Verhalten wird es nur mit Todo Listen btw Todos geben, die ein Wiederholungsmuster gesetzt haben.

> die geschichte mit dem datum relativ zum eledigt datum hat anscheinen einen kleinen bug.
> ich hatte den haken ja gesetzt beim erstellen der wiederholung und es hat nicht wie erwartet funktioniert.
> nun habe ich das weiter untersucht und bemerkt das der haken beim ersten erstellen des termins nicht immer mit gespeichert wird.
> denn wenn man die den intervall nochmals an sieht ist der haken dann nicht mehr drinn.
> daher auch verhält sich der termin dann natürlich wie ohne den haken.

Danke für den Hinweis! Ich habe dazu [dieses Issue](https://gitlab.com/rpdev/opentodolist/-/issues/620) auf GitLab angelegt, um das weiter zu untersuchen und zu fixen.

> aber auch hier ist es so das beim mehrfachen abhaken am selben tag der termin immer im intervall immer weiter geschoben wird.

Genau - das ist so gewollt.

> ich finde das wiederspricht sich dann mit der beschreibung "relativ zum datum der erledigung".

Vielleicht gibt es eine andere (bessere) Formulierung für die Option, aber nein - es ist genau so gemeint:

- Standardmäßig (also wenn die Option aus ist) bleiben die Items im selben "Raster" (also ein Item das z.B. auf einen Montag gelegt wurde wird dann auch wieder auf einen Montag fallen).
- Ist die Option aktiviert, verschiebt sich das Item und kann dann eben auf einen anderen Wochentag fallen.

Je nach Use Case haben beide Varianten ihre Daseinsberechtigung. Ich sehe aber auch definitiv deinen Punkt, dass man so (versehentlich) ein Item zu weit in die Zukunft verschiebt. Ich habe daher [dieses Issue](https://gitlab.com/rpdev/opentodolist/-/issues/621) auf GitLab aufgemacht, um eine entsprechende Änderung zu implementieren und so zumindest versehentliches "Verschieben" zu vermeiden.

> üblicher weise habe ich ein konto mit der DAV schnittstelle meines seafile-servers verbunden in dem alle listen und aufgaben liegen.
> da ist der zugriff logischer weise langsamer als lokal.
> es könnte natürlich auch eine cache einstellung sein die das verhalten beim speichern des hakens beeinflusst.
> ich muss mal schauen ob sich da etwas machen lässt.

Gut zu wissen. Nur zur Hintergrundinformation (falls du dein Setup genauer untersuchen möchtest):

OpenTodoList macht keine direkten Zugriffe auf den Server, wenn sich etwas in einer Bibliothek ändert. In der Tat ist die App darauf aufgelegt, dass du mit einer Bibliothek auch dann arbeiten kannst, wenn du komplett "offline" bist - stattdessen wird dann später ein "Sync" angestoßen, der versucht, den lokalen Stand mit dem Stand auf dem Server abzugleichen. Hier kann es allerdings zu Problemen kommen:

- Wenn mehrere Personen mit der selben Bibliothek arbeiten oder man selbst von mehreren Geräten aus Einträge ändert, kann es zu Sync Konflikten kommen. Derzeit verwendet die OpenTodoList die Option "Server Wins" um solche Konflikte aufzulösen, d.h. wenn die App auf einem Gerät feststellt, dass ein Eintrag sowohl lokal als auch auf dem Server geändert wurde, wird die Variante vom Server übernommen.
  -  Um die Wahrscheinlichkeit für solche Konflikte möglichst gering zu halten, stößt die App nach Änderungen jeweils einen Sync an, so dass Änderungen sofort auf den Server gepusht werden. Das geht natürlich nur, wenn man online ist.
-  Ein weiteres (tatsächlich größeres) Problem ist an dieser Stelle "WebDAV" selbst. Bzw. die Art, wie viele Server diesen Standard implementieren. Damit die OpenTodoList Bibliotheken ordentlich und sauber synchronisieren kann, wird vorausgesetzt, dass der Server ordentliche _eTags_ implementiert - das ist ein Verfahren, um Client-seitig zu erkennen, ob sich Dateien auf dem Server geändert haben. Leider gibt es sehr viele Implementierungen, die WebDAV entweder nicht ganz oder sogar falsch implementieren.
  - Ich kann an dieser Stelle NextCloud bzw. ownCloud als Server empfehlen - diese implementieren WebDAV sauber, so dass die OpenTodoList sehr gut mit diesen Servern zusammenarbeiten kann. Andere Server gehen auch, allerdings kann es hier auch zu Problemen kommen - leider muss man jeden Typ Server einzeln evaluieren und potentielle Probleme mit deren WebDAV Implementierungen untersuchen. Mit Seafile habe ich bisher noch nicht gearbeitet - daher kann ich leider nicht sagen, ob deren Implementierung u.U. Probleme machen könnte.


> beim testen ist mir dann aufgefallen das es recht mühsam ist immer das kleine symbol zu treffen um den intervall einzustellen.
> (gerade heute habe ich schon 2 tonnen pellets in den keller geschleppt.)
> ich benutze hauptsächlich die desktop app (windows).
> da wäre es aus meiner sicht eine verbesserung wenn man zum symbol auch noch den text als schaltfläche hätte.
> also den text "kein muster gesetzt" direkt anklicken kann um den intervall einzustellen.
> da das symbol rechtsbündig ist muss man immer so weit rüber mit der maus. und die menschen sind doch so faul...

Ist aufgenommen - siehe [hier](https://gitlab.com/rpdev/opentodolist/-/issues/622) 😉 

Last but not least, auch für das Schließen von Einträgen sobald alle enthaltenen Einträge als "Done" markiert wurden, habe ich ein [Issue](https://gitlab.com/rpdev/opentodolist/-/issues/623) gemacht.

Ich hoffe, dass damit erstmal alles ordentlich aufgenommen ist.

Viele Grüße und ein schönes Wochenende!

**Comment by real-easy** [comment]
super, ich bin sprachlos....

ich danke dir schon mal für die absicht hier einiges umzusetzen.
das ich viel mehr als ich erwarten konnte.

bitte nur kein stress, ich (und sicher die anderen auch) weiss wie stressig es manchmal zu geht.
außerdem will und sollte man ja nicht die ganze freizeit für ein projekt opfern.
es ist ja schon das beste wenn man weiss das überhaupt noch daran gearbeitet wird.


nochmal zum DAV...
derzeit bin ich der einzige user für die todoliste, zeitgleiche änderungen aus mehreren richtungen sind vorerst ausgeschlossen.
ich habe zwar meiner frau eine einkaufsliste in einer extra bib angelegt, was sie aber bisher erfolgreich ignoriert hat.

ich denke mal das seafile mit dem DAV auch gut umgehen kann, das ist ja schließlich das hauptgeschäft dieses servers.
auch die seafile app, verhält sich wie eine DAV app, nennt sich nur eben nicht so.

ich werde das problem noch eine weile im auge behalten.
seit dem ich wieder zu hause teste, gabs dem effekt mit dem nicht setzen des hakens noch nicht wieder.

das letze mal habe ich aus der ferne über vpn getestet da konnte ich das mehrfach generieren.
bei seafile selbst gabs aber über vpn bisher keine side-effekte dieser art.
ich würde die wichtung das für dieses problem nicht zu hoch ansetzen.
wenn die todos erstmal richtig gesetzt sind, ist das ja nicht mehr wichtig.

nochmals besten dank und gleichfall ein super wochenende.
beste grüße  easy

**Comment by mhoeher** [comment]
Hallo @real-easy,

nur ein kurzes Lebenszeichen: Ich war die letzten Wochen leider ziemlich beschäftigt (leider auch mit nicht-OpenTodoList Themen). Ich hoffe, dass ich in den nächsten zwei bis drei Wochen noch ein paar nette Feature fürs nächste Release implementiert bekomme.

Ich habe mich gerade an das "automatische" Schließen von Todolisten/Todos gemacht (siehe https://gitlab.com/rpdev/opentodolist/-/issues/623). Hier eine kleine "Kostprobe" wie das ganze ausschaut:


https://github.com/mhoeher/opentodolist/assets/1911135/dd78206e-d2e1-47d6-bcc4-84671c22e343

Funktioniert sowohl für Todos als auch Todolisten (falls diese ein Zieldatum haben).

**Comment by real-easy** [comment]
hallo martin,

ich habe auch gerade genug um die ohren, baue heizung, der pellet-ofen muss noch angeschlossen werden.
seit dem WE habe ich endlich wasser im system und seit heute funktioniert der heizstab wieder richtig.
die todolist unterstützt mich aber bestens dabei.
fehlende teile werden sofort in die einkaufsliste gepackt, ideen und verbesserungen haben auch eine liste.
genau wie die offnen punkte.
zur wartung komme ich aber aktuell auch nicht, daher fehlen die neuen features aktuell noch nicht so sehr.

das abhaken der liste sah schon sehr gut aus.
ich denke in der ecke des programms kannst du auch gleich den umgekehrten weg mit einpflegen.
so das eine liste mit wiederhol-termin auch wieder enthakt wird.

danke für die mühe und beste grüße von T nach S

**Comment by mhoeher** [comment]
> ich denke in der ecke des programms kannst du auch gleich den umgekehrten weg mit einpflegen.
so das eine liste mit wiederhol-termin auch wieder enthakt wird.

Das ist direkt einer der nächsten Punkte, die auf der Liste stehen 😉

**Comment by mhoeher** [comment]
So, nochmal ein kurzes Update. Ich habe ein weiteres Feature aus der Liste hier implementiert:

- Todos und andere Items, die sich wiederholen und deren "aktuelle" Instanz als fertig markiert wurden, werden jetzt leicht ausgegraut dargestellt.
- Außerdem wird - wenn man versucht, ein solches Item abzuhaken - ein kleiner Tooltip angezeigt, in dem bestätigt werden muss, ob man diese zukünftige Instanz wirklich schon vorzeitig als fertig markieren will.

So sieht das ganze "in action" aus:


https://github.com/mhoeher/opentodolist/assets/1911135/aa22c037-a1c7-47fd-a5ef-507181f5e640

**Comment by real-easy** [comment]
super, großartig.

**Comment by mhoeher** [comment]
Und noch ein kurzes Update hier:

- Der Bug im Editor zum Einstellen der Wiederholungsmuster ist jetzt behoben.
- Außerdem wurde der Editor überarbeitet, so dass man nun die komplette "Zeile" anklicken/antappen kann, um eine Aktion zu triggern.

https://github.com/mhoeher/opentodolist/assets/1911135/0089b275-6097-4b00-8bba-09880cbca659

**Comment by real-easy** [comment]
klasse, da möchte man fast das die WE weiterhin so mistwetter bringen. 
gibts die änderungen schon in kompilierter form ?

**Comment by mhoeher** [comment]
Ja, zumindest für die meisten Plattformen. Dazu am besten in die CI/CD Pipelines auf dem "development" Branch schauen. Hier ist der aktuellste Run: https://gitlab.com/rpdev/opentodolist/-/pipelines/918598623

Von dort können für viele Systeme vorkompilierte Versionen heruntergeladen werden. Bei Fragen einfach Bescheid geben 😉

**Comment by real-easy** [comment]
hat geklappt, danke

**Comment by mhoeher** [comment]
Und nochmal ein kurzes Update: Wenn eine die aktuelle Instanz einer Todo Liste bzw eines Todos als erledigt markiert und eine neue Instanz erstellt wird, werden nun auch alle enthaltenen Einträge (rekursiv) wieder als "unfertig" markiert. Hier ein kleines Video, wie das ganze aussieht:

https://github.com/mhoeher/opentodolist/assets/1911135/4304d3d8-ed5a-4df8-b34b-ce067735641a

Da ich schon gut "over time" bin mache ich mich diese Woche daran, eine neue Version der OpenTodoList zu veröffentlichen, so dass die gesammelten neuen Feature auch allgemein zugänglich werden 😉 

Ich denke/hoffe, dass jetzt alle Punkte bzgl. deiner Anfrage gelöst sind und würde dieses Ticket damit schließen. Falls du noch Verbesserungsvorschläge hast oder Bugs findest - bitte einfach neue Issues aufmachen (idealerweise "drüben" auf GitLab, ansonsten auch hier).
