### ISSUE TITLE
Attachment deletedn

### ISSUE THREAD

**Issue by Rubylion** [mhoeher/opentodolist#9]
As an Attachment has been added to a task, f.e. image, it is not displayed, but more problematic, when I want to remove the attachment, also the file is deletetld, what shouldn't happen in my opinion, because often you just want to remove the attachment, but nit the file on the sdcard.

**Comment by mhoeher** [comment]
Hi @Rubylion,

attachments are supposed for all kinds of files, this is why there is no integrated "viewer" right now. However, clicking/tapping on an attachment should open the file in a suitable viewer.

When attaching files, they are actually copied over into your library folder. Consequentially, when deleting an attachment, the corresponding file inside the collection is deleted; however, the original file should still remain in place.

I will check the current implementation if there's anything wrong. It would be great if you could also cross check on your side if the behaviour is reproducible  ;-) Thank you!

**Comment by mhoeher** [comment]
I created an issue in the project's bug tracker over on GitLab.com: https://gitlab.com/rpdev/opentodolist/issues/202

**Comment by mhoeher** [comment]
Hi @Rubylion,

I tried to reproduce the behaviour you described on a Vanilla Android phone (a Nexus 6P). However, I cannot confirm that the original file is deleted as soon as you detach a file. Could you please cross check on your side if the original file is indeed deleted? Or - just in case I got you wrong - provide more details on what you think the app should behave?

Thanks a lot!

**Comment by mhoeher** [comment]
I reviewed the code which handles images and also attachments and found nothing suspicious. There was another issue in the app which might have hit you - for details, please see the [GitLab tracking issue](https://gitlab.com/rpdev/opentodolist/issues/202) I created for this one.
