### ISSUE TITLE
Erweiterungsanfrage siehe Diskussions-Board

### ISSUE THREAD

**Issue by imperiumsources** [mhoeher/opentodolist#91]
hallo,

anscheinend wird das Diskussions-Board nicht genutzt oder gesehen.
Deshalb hier der Link dazu ^^

https://github.com/mhoeher/opentodolist/discussions/89

**Comment by mhoeher** [comment]
Hallo @imperiumsources,

gesehen schon (zumindest bekomme ich emails von GitHub 😉), leider fehlt mir derzeit etwas die Zeit, darum kommen Antworten nicht immer "instant".

Ich mache dieses Issue erstmal zu - da du deine Anfragen im Forum gemacht hast, unterstelle ich erstmal, dass - was auch immer dort diskutiert wird - nicht 1:1 auf Arbeitspakete abgebildet wird (bzw erst nach ausführlicher Diskussion). 😉
