### ISSUE TITLE
Request: Reset Tasklist to "all due"

### ISSUE THREAD

**Issue by DamageIncorporated** [mhoeher/opentodolist#94]
Hey, 

i use Opentodolist for newspaper delivery.

Some Background:

> The "digital workflow" of my publisher and employer is still limited to PDF-Adresslists, that I can print on paper and carry with me. Welcome to the 21st century ;-)

>  To improve my personal workflow, I transfer my current address list to open todo list on the linux desktop. This alone is a great improvement over writing lists directly on the phone and the my cause for choosing OTL as an application.

Now I change delivery order from alphabetical to geographical: 

The order of house numbers in the list now resembles the order I find in reality.

On my delivery tour, I check off every name in the list when I drop a paper in a postbox.

My task list layout looks like this: 

- Task List is a Delivery district (like 176800)
- Task is a Street (Musterstraße)
- Subtask is a housenumber and name (13 Müller)

In this (and possibly other) scenarios, tasks on a list must be completed repeatedly, in my case daily.
 
I wish there was a simple button to reset a task list to "mark all as due". 

ATM, I uncheck every item manually each morning.

Thank you for this great application with desktop companion and for considering my request 😊

**Comment by mhoeher** [comment]
Hi @DamageIncorporated,

first of all, sorry for the late reply. I am currently on a business trip in India and hence, barely found any time checking my private messages.

Regarding your request: I think it definitely makes sense! I created a tracking issue over on [GitLab](https://gitlab.com/rpdev/opentodolist/-/issues/639) and assigned it to the next version (i.e. it would be due end of December). Will let you know once a test version is available 😉

**Comment by DamageIncorporated** [comment]
Hey @mhoeher ,

that's great to read!

Never mind about the late reply. Didn't expect anything more timely :-)

I'm still in the transition from [rshopping](rshopping.net) for my daily delivery lists, so December is fine with me..
ATM, only new delivery districts go directly to OpenTodoList to check if I can use it on a daily (nightly) basis while learning.

I hope you don't mind when I send more issues as I am testing. I don't have the next one in mind yet, but when I use an App every night in this scenario I usually find some :-) 

Thank you for this fine project!

**Comment by mhoeher** [comment]
Hi @DamageIncorporated,

maybe some good news already right now: You won't necessarily have to wait for December. The app is using a CI/CD approach, so particularly for Windows (from where you most likely would trigger the mass-mark-undone) you should be able to test way earlier 😉 

Also, if you find more features you'd like to see in the app: Feel free to open additional requests, they are very welcome! Just bear with me that implementation sometimes can take quite a bit (some features are relatively easy to implement, other require more changes and as this app is developed in my free time, this can take a bit).

**Comment by mhoeher** [comment]
Hi @DamageIncorporated,

I implemented the requested feature and will merge it to the develop branch. It will be part of the next release of the app (due end of the year). If you like, you can download pre-build versions of the app from the jobs of this pipeline for immediate testing: https://gitlab.com/rpdev/opentodolist/-/pipelines/1056968941

One note: I also used that chance to clean up the user interface a bit. The toolbar now consistently contains only 4 items that pop up the available actions as menus. Additionally, the app now has a menu bar on some platforms (macOS, Windows and Linux distributions, given they support the global app menu standard).

The requested new actions (mark all as done and mark all as undone) can be found in the edit menu If used within a todo list, all todos and tasks are marked as done/undone. If executed when a todo is open, only the tasks within this todo are marked as undone/done.

Hope that's what you expected and aids in your use case 😉

**Comment by mhoeher** [comment]
Short update: In case you want to test the Windows version of the app... pls check out this pipeline: https://gitlab.com/rpdev/opentodolist/-/pipelines/1061224518

There was an issue with the Windows build in the previous pipeline I linked (basically, the Windows installer was not properly built...)
