### ISSUE TITLE
Minor: [Android] Launcher-Icon disappeared on update to 3.46.0 

### ISSUE THREAD

**Issue by DamageIncorporated** [mhoeher/opentodolist#95]
Hey, 

as stated above, this is no real problem, but I noticed yesterday, that I see the generic "Android-on-a-blue-circle-icon" when look up OpenTodoList in my launcher.

F-droid says that a new version dropped in the IzzyOnDroid Repo yesterday, so I think that this update killed the icon..

Everyhing else is fine 😉

**Comment by mhoeher** [comment]
Hi @DamageIncorporated,

thanks for letting me know. Yes, a new release just got available (and AFAIR, Izzy pulls them in automatically, so they usually get available via his F-Droid repo rather quickly). The latest release in fact was supposed to fix an issue with the launcher icon on (some) Android devices. Not sure why it killed it on your device.

Could you provide more details, like device you are on and OS version?

Actually, the APK distributed via F-Droid and the AAB which is uploaded to the Play store are build from the same code base (in one go), so I somehow wouldn't expect any differences from there.

**Comment by DamageIncorporated** [comment]
I use a rather old Samsung Galaxy A5 2017 (SM-A520F), not rooted but degoogled and with open bootloader:

- Android Version 11
- /e/ OS 1.13
- and finally: KISS Launcher 3.20.1

;-)

**Comment by mhoeher** [comment]
Hi @DamageIncorporated,

sorry again for the late reply, the past few days were quite busy and on top, I managed to catch a bad cold 🤧

The "good" news is, I managed to reproduce the issue on an older Android device. Maybe this really has to do with the OS version... the latest release consistently switched to using scalable icons, maybe this was a too bold move 🤷 

I'll try to push out a bugfix release as soon as I can.

For your reference, here is the tracking ticket over on GitLab: https://gitlab.com/rpdev/opentodolist/-/issues/640

**Comment by mhoeher** [comment]
Hi @DamageIncorporated,

one short update: I found the issue. It has - in fact - nothing to do with the Android version. The Qt Creator IDE (which I mainly use to hack on the app) removed the icon from the android manifest file and this mistake somehow slipped the code review process. A fix is already on the way to be merged and I'll try to push out a hot fix version in the following days.

**Comment by mhoeher** [comment]
Hi @DamageIncorporated,

good news: I just pushed out a hot fix release which should bring the icon back on Android. The release might take some time in the Play Store (as they'll review before publishing there). For F-Droid, it should be picked up soon, too.
