### ISSUE TITLE
(Hidden) error on Windows

### ISSUE THREAD

**Issue by wimg** [mhoeher/opentodolist#96]
Starting the application results in nothing but event viewer shows :
Application popup: OpenTodoList.exe - Entry Point Not Found : The procedure entry point SystemParametersInfoForDpi could not be located in the dynamic link library F:\Program Files\OpenTodoList\bin\Qt6Gui.dll. 

This is on Windows 8.1

**Comment by mhoeher** [comment]
Hi @wimg,

thanks for raising this issue!

I just checked and according to this: https://doc.qt.io/qt-6.5/supported-platforms.html

Qt (which is the underlying framework powering the app) does not support Windows 8.1. This seems legit, as according to Microsoft itself, Windows 8.1 is no longer supported: https://learn.microsoft.com/en-us/lifecycle/products/windows-81

So, unfortunately, I currently see no means to support you here. If you feel comfortable with this, you could try to build the app on your own using a slightly older version of Qt, but typically, the app adopts new features of the framework rather quickly, so this might not be easy or feasible at all. Sorry... 😞 Generally, looking at the official MS docs, I would recommend upgrading to a supported platform urgently, as running an EoLed product will have far more severe downsides beyond some apps not running on them anymore.

**Comment by wimg** [comment]
Hi @mhoeher ,

I understand and already suspected this might be the issue.

I plan on upgrading once I've taken a backup ;-)

Thanks for looking into it !
